package dbutil

import "backend/internal/common/enums"

// PostgreSQLTypeMap maps PostgreSQL DB types to our internal FieldType.
var PostgreSQLTypeMap = map[string]enums.FieldType{
	"integer":     enums.FieldTypeInteger,
	"serial":      enums.FieldTypeInteger,
	"serial2":     enums.FieldTypeInteger,
	"serial4":     enums.FieldTypeInteger,
	"intserial":   enums.FieldTypeInteger,
	"int2":        enums.FieldTypeInteger,
	"int4":        enums.FieldTypeInteger,
	"bigint":      enums.FieldTypeLong,
	"bigserial":   enums.FieldTypeLong,
	"serial8":     enums.FieldTypeLong,
	"int8":        enums.FieldTypeLong,
	"timestamptz": enums.FieldTypeDatetime,
	"timestamp":   enums.FieldTypeDatetime,
	"float":       enums.FieldTypeFloat,
	"float4":      enums.FieldTypeFloat,
	"double":      enums.FieldTypeDouble,
	"float8":      enums.FieldTypeDouble,
	"text":        enums.FieldTypeString,
	"char":        enums.FieldTypeString,
	"json":        enums.FieldTypeString,
	"jsonb":       enums.FieldTypeString,
	"varchar":     enums.FieldTypeString,
	"bool":        enums.FieldTypeBoolean,
	"boolean":     enums.FieldTypeBoolean,
	"blob":        enums.FieldTypeBlob,
}

// MariaDBTypeMap maps MariaDB DB types to our internal FieldType.
var MariaDBTypeMap = map[string]enums.FieldType{
	"int":        enums.FieldTypeInteger,
	"smallint":   enums.FieldTypeInteger,
	"tinyint":    enums.FieldTypeInteger,
	"mediumint":  enums.FieldTypeLong,
	"bigint":     enums.FieldTypeLong,
	"float":      enums.FieldTypeFloat,
	"double":     enums.FieldTypeDouble,
	"decimal":    enums.FieldTypeDouble,
	"char":       enums.FieldTypeString,
	"varchar":    enums.FieldTypeString,
	"text":       enums.FieldTypeString,
	"tinytext":   enums.FieldTypeString,
	"mediumtext": enums.FieldTypeString,
	"json":       enums.FieldTypeString,
	"bit":        enums.FieldTypeLong,
	"date":       enums.FieldTypeDatetime,
	"time":       enums.FieldTypeDatetime,
	"datetime":   enums.FieldTypeDatetime,
	"timestamp":  enums.FieldTypeDatetime,
	"tinyblob":   enums.FieldTypeBlob,
	"blob":       enums.FieldTypeBlob,
	"mediumblob": enums.FieldTypeBlob,
	"longblob":   enums.FieldTypeBlob,
}

// SQLServerTypeMap maps SQL Server DB types to our internal FieldType.
var SQLServerTypeMap = map[string]enums.FieldType{
	"int":            enums.FieldTypeInteger,
	"smallint":       enums.FieldTypeInteger,
	"tinyint":        enums.FieldTypeInteger,
	"bigint":         enums.FieldTypeLong,
	"float":          enums.FieldTypeFloat,
	"real":           enums.FieldTypeFloat,
	"decimal":        enums.FieldTypeDouble,
	"numeric":        enums.FieldTypeDouble,
	"char":           enums.FieldTypeString,
	"varchar":        enums.FieldTypeString,
	"text":           enums.FieldTypeString,
	"nchar":          enums.FieldTypeString,
	"nvarchar":       enums.FieldTypeString,
	"ntext":          enums.FieldTypeString,
	"bit":            enums.FieldTypeBoolean,
	"date":           enums.FieldTypeDatetime,
	"time":           enums.FieldTypeDatetime,
	"datetime":       enums.FieldTypeDatetime,
	"datetime2":      enums.FieldTypeDatetime,
	"datetimeoffset": enums.FieldTypeDatetime,
	"binary":         enums.FieldTypeBlob,
	"varbinary":      enums.FieldTypeBlob,
}
