// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2-1

package types

type ApiKeyCreateReq struct {
	Name         string   `json:"name"`
	Permission   string   `json:"permission,optional"`
	UsageType    string   `json:"usageType,optional"`
	KeyType      string   `json:"keyType,optional"`
	ResourceKeys []string `json:"resourceKeys,optional"`
	ExpireTime   int64    `json:"expireTime,optional"`
}

type ApiKeyIdReq struct {
	ApiKeyId int64 `path:"apiKeyId"`
}

type ApiKeyUpdateReq struct {
	ApiKeyId   int64  `path:"apiKeyId"`
	Name       string `json:"name,optional"`
	Permission string `json:"permission,optional"`
}

type AssetBindReq struct {
	FileId        int64  `json:"fileId"`
	OwnerType     string `json:"ownerType"`
	OwnerId       string `json:"ownerId"`
	PermissionKey string `json:"permissionKey,optional"`
}

type AssetListReq struct {
	PageNo    int    `form:"pageNo,optional"`
	PageSize  int    `form:"pageSize,optional"`
	OwnerType string `form:"ownerType,optional"`
	OwnerId   int64  `form:"ownerId,optional"`
}

type AssetUploadReq struct {
	FileName    string `json:"fileName"`
	ContentType string `json:"contentType,optional"`
	Size        int64  `json:"size,optional"`
	Sha256      string `json:"sha256,optional"`
	StorageKey  string `json:"storageKey,optional"`
	IsPublic    bool   `json:"isPublic,optional"`
	Business    string `json:"business,optional"`
	UseBy       string `json:"useBy,optional"`
}

type AssetUploadResp struct {
	UploadUrl string `json:"uploadUrl"`
	FilePath  string `json:"filePath"`
	FileUrl   string `json:"fileUrl,optional"`
}

type AuditLogPageReq struct {
	PageNo          int    `json:"pageNo,optional"`
	PageSize        int    `json:"pageSize,optional"`
	ScopeType       int    `json:"scopeType,optional"`
	ScopeId         int64  `json:"scopeId,optional"`
	ResType         string `json:"resType,optional"`
	BusinessType    string `json:"businessType,optional"`
	OperatorKeyword string `json:"operatorKeyword,optional"`
	Code            int    `json:"code,optional"`
	StartTime       string `json:"startTime,optional"`
	EndTime         string `json:"endTime,optional"`
}

type AuthWhoamiResp struct {
	UserID        int64    `json:"userID"`
	UserName      string   `json:"userName"`
	Email         string   `json:"email"`
	WorkspaceID   int64    `json:"workspaceID"`
	WorkspaceName string   `json:"workspaceName"`
	ApiKeyName    string   `json:"apiKeyName"`
	KeyPrefix     string   `json:"keyPrefix"`
	Permissions   []string `json:"permissions"`
	Roles         []string `json:"roles"`
	KeyType       string   `json:"keyType"`
}

type BrowseReq struct {
	Path             string `json:"path,optional"`
	MaxDepth         int64  `json:"max_depth,optional"`
	IncludeMetadata  bool   `json:"include_metadata,optional"`
	IncludeLeafValue bool   `json:"include_leaf_value,optional"`
}

type BrowseResp struct {
	Tree []OpenapiNodeInfo `json:"tree"`
}

type CliAuthBindReq struct {
	SetupCode  string `json:"setupCode"`
	Name       string `json:"name,optional"`
	Permission string `json:"permission,optional"`
}

type CliAuthBindResp struct {
	ApiKey        string `json:"apiKey"`
	Name          string `json:"name"`
	Permission    string `json:"permission"`
	WorkspaceName string `json:"workspaceName,optional"`
}

type CliAuthStatusReq struct {
	SetupCode string `json:"setupCode"`
}

type CliAuthStatusResp struct {
	Status        string `json:"status"`
	ApiKey        string `json:"apiKey"`
	WorkspaceName string `json:"workspaceName"`
	ExpiresAt     string `json:"expiresAt"`
}

type ContainerAppIdReq struct {
	AppId int64 `path:"appId"`
}

type ContainerAppSaveReq struct {
	AppId          int64  `path:"appId,optional"`
	Name           string `json:"name"`
	Description    string `json:"description,optional"`
	IconAssetId    int64  `json:"iconAssetId,optional"`
	EntryUrl       string `json:"entryUrl"`
	OpenInPlatform bool   `json:"openInPlatform,optional"`
}

type ContainerAppVisibilityReq struct {
	AppId   int64 `path:"appId"`
	Enabled bool  `json:"enabled"`
}

type CreateResp struct {
	Success bool                  `json:"success"`
	Results []OpenapiCreateResult `json:"results"`
}

type CurrentUserConfigReq struct {
	HomePage     string `json:"homePage,optional"`
	MainLanguage string `json:"mainLanguage,optional"`
}

type CurrentUserConfigResp struct {
	UserId       int64  `json:"userId"`
	HomePage     string `json:"homePage,optional"`
	MainLanguage string `json:"mainLanguage,optional"`
}

type CurrentUserPasswordReq struct {
	OldPassword string `json:"oldPassword,optional"`
	Password    string `json:"password,optional"`
	NewPassword string `json:"newPassword"`
}

type CurrentUserProfileReq struct {
	FirstName string `json:"firstName,optional"`
	Email     string `json:"email,optional"`
	Phone     string `json:"phone,optional"`
}

type CurrentUserResp struct {
	UserId              int64    `json:"userId"`
	UserName            string   `json:"userName"`
	NickName            string   `json:"nickName"`
	Email               string   `json:"email"`
	Phone               string   `json:"phone"`
	RoleCode            string   `json:"roleCode,optional"`
	ForceChangePassword bool     `json:"forceChangePassword"`
	ResourceKeys        []string `json:"resourceKeys"`
	UiActions           []string `json:"uiActions"`
}

type Empty struct {
}

type Envelope struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,optional"`
}

type FileIdReq struct {
	FileId int64 `path:"fileId"`
}

type FlowDataReq struct {
	FlowId   int64  `path:"flowId"`
	FlowData string `json:"flowData"`
}

type FlowDeployReq struct {
	FlowId   int64  `path:"flowId"`
	FlowData string `json:"flowData,optional"`
}

type FlowIdReq struct {
	FlowId int64 `path:"flowId"`
}

type FlowListReq struct {
	FlowType string `form:"flowType,optional"`
	ParentId int64  `form:"parentId,optional"`
	Keyword  string `form:"keyword,optional"`
}

type FlowMarkReq struct {
	FlowId int64 `path:"flowId"`
	Pinned bool  `json:"pinned"`
}

type FlowMockField struct {
	Name      string `json:"name"`
	FieldType string `json:"type,optional"`
}

type FlowSaveReq struct {
	FlowId          int64           `path:"flowId,optional"`
	SourceId        int64           `json:"sourceId,optional"`
	ParentId        int64           `json:"parentId,optional"`
	FlowType        string          `json:"flowType"`
	NodeType        string          `json:"nodeType"`
	Name            string          `json:"name"`
	Description     string          `json:"description,optional"`
	Template        string          `json:"template,optional"`
	UnsNodeIds      []int64         `json:"unsNodeIds,optional"`
	MockData        bool            `json:"mockData,optional"`
	MockTopic       string          `json:"mockTopic,optional"`
	MockFields      []FlowMockField `json:"mockFields,optional"`
	MockTriggerMode string          `json:"mockTriggerMode,optional"`
}

type FlowStatusReq struct {
	FlowId int64  `path:"flowId"`
	Status string `json:"status"`
}

type GatewayRouteListResp struct {
	List  []GatewayRouteReq `json:"list"`
	Total int64             `json:"total"`
}

type GatewayRouteReq struct {
	RouteKey    string   `json:"routeKey"`
	Name        string   `json:"name"`
	Description string   `json:"description,optional"`
	TargetType  string   `json:"targetType"`
	MatchType   string   `json:"matchType"`
	PathPattern string   `json:"pathPattern"`
	Methods     []string `json:"methods,optional"`
	TargetUrl   string   `json:"targetUrl,optional"`
	TargetPath  string   `json:"targetPath,optional"`
	StripPrefix bool     `json:"stripPrefix,optional"`
	RewritePath string   `json:"rewritePath,optional"`
	AuthPolicy  string   `json:"authPolicy"`
	ResourceKey string   `json:"resourceKey,optional"`
	TimeoutMs   int      `json:"timeoutMs,optional"`
	Priority    int      `json:"priority,optional"`
	Enabled     bool     `json:"enabled"`
}

type HistoryAggregation struct {
	Interval string                    `json:"interval"`
	Function string                    `json:"function,optional"`
	Field    string                    `json:"field,optional"`
	Fields   []HistoryAggregationField `json:"fields,optional"`
}

type HistoryAggregationField struct {
	Name     string `json:"name"`
	Function string `json:"function,optional"`
}

type HistoryQueryMeta struct {
	Aggregated          bool   `json:"aggregated"`
	Sampled             bool   `json:"sampled"`
	RawTotal            int64  `json:"rawTotal"`
	ReturnedTotal       int64  `json:"returnedTotal"`
	RequestedIntervalMs int64  `json:"requestedIntervalMs,optional"`
	ActualIntervalMs    int64  `json:"actualIntervalMs,optional"`
	Strategy            string `json:"strategy,optional"`
}

type HistoryReq struct {
	Topics      []string            `json:"topics"`
	StartTime   string              `json:"start_time"`
	EndTime     string              `json:"end_time"`
	Aggregation *HistoryAggregation `json:"aggregation,optional"`
	Page        int64               `json:"page,optional"`
	Size        int64               `json:"size,optional"`
}

type HistoryResp struct {
	Success bool                 `json:"success"`
	Results []OpenapiHistoryItem `json:"results"`
	Page    int64                `json:"page"`
	Size    int64                `json:"size"`
	Total   int64                `json:"total"`
}

type HomeRecentItem struct {
	Key          string `json:"key"`
	ResourceKey  string `json:"resourceKey"`
	ResourceName string `json:"resourceName"`
	ResourceType string `json:"resourceType"`
	BusinessType string `json:"businessType"`
	RoutePath    string `json:"routePath"`
	Icon         string `json:"icon"`
	OperatedAt   int64  `json:"operatedAt"`
}

type HomeRecentReq struct {
	Limit int `form:"limit,optional"`
}

type I18nMessagesReq struct {
	Lang string `form:"lang"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type InfoResp struct {
	Name         string   `json:"name"`
	Version      string   `json:"version"`
	Capabilities []string `json:"capabilities"`
	MqttBroker   string   `json:"mqttBroker"`
}

type JobIdReq struct {
	JobId string `path:"jobId"`
}

type ListResp struct {
	List  []interface{} `json:"list"`
	Total int64         `json:"total"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token               string   `json:"token"`
	UserId              int64    `json:"userId"`
	UserName            string   `json:"userName"`
	NickName            string   `json:"nickName"`
	Email               string   `json:"email"`
	Phone               string   `json:"phone"`
	RoleCode            string   `json:"roleCode,optional"`
	IsRandomPwd         bool     `json:"isRandomPwd"`
	ForceChangePassword bool     `json:"forceChangePassword"`
	ResourceKeys        []string `json:"resourceKeys"`
	UiActions           []string `json:"uiActions"`
}

type NamespaceNode struct {
	Name             string            `json:"name"`
	Type             string            `json:"type,optional"`
	Children         []NamespaceNode   `json:"children,optional"`
	TopicType        string            `json:"topicType,optional"`
	Fields           []SchemaField     `json:"fields,optional"`
	Description      string            `json:"description,optional"`
	DisplayName      string            `json:"displayName,optional"`
	ExtendProperties map[string]string `json:"extendProperties,optional"`
	Alias            string            `json:"alias,optional"`
	EnableHistory    *bool             `json:"enableHistory,optional"`
}

type NodeCreateReq struct {
	Namespace []NamespaceNode `json:"namespace"`
}

type NodeDeleteReq struct {
	Topics []string `json:"topics"`
}

type NodeIdReq struct {
	NodeId int64 `path:"nodeId"`
}

type NodeRedMissingNodeCleanupReq struct {
	FlowType string `json:"flowType,optional"`
}

type NodeRedMissingNodeDeleteReq struct {
	Id       string `form:"id"`
	FlowId   string `form:"flowId,optional"`
	Scope    string `form:"scope,optional"`
	FlowType string `form:"flowType"`
}

type NodeRedMissingNodeListReq struct {
	FlowType string `form:"flowType"`
}

type NodeRedNodeTypeListReq struct {
	FlowType string `form:"flowType"`
}

type NodeUpdateReq struct {
	Path             string            `json:"path"`
	Name             string            `json:"name,optional"`
	Description      string            `json:"description,optional"`
	DisplayName      string            `json:"displayName,optional"`
	ExtendProperties map[string]string `json:"extendProperties,optional"`
	Fields           []SchemaField     `json:"fields,optional"`
	Alias            string            `json:"alias,optional"`
	EnableHistory    *bool             `json:"enableHistory,optional"`
	UpdateMask       []string          `json:"updateMask,optional"`
}

type OAuthAuthorizeReq struct {
	ResponseType        string `form:"responseType"`
	ClientId            string `form:"clientId"`
	RedirectUri         string `form:"redirectUri"`
	Scope               string `form:"scope,optional"`
	State               string `form:"state,optional"`
	CodeChallenge       string `form:"codeChallenge,optional"`
	CodeChallengeMethod string `form:"codeChallengeMethod,optional"`
}

type OAuthClientReq struct {
	Id             int64    `path:"id,optional"`
	ClientName     string   `json:"clientName"`
	RedirectUris   []string `json:"redirectUris"`
	AllowedOrigins []string `json:"allowedOrigins,optional"`
	AppId          int64    `json:"appId,optional"`
}

type OAuthTokenReq struct {
	GrantType    string `json:"grantType"`
	Code         string `json:"code,optional"`
	RedirectUri  string `json:"redirectUri,optional"`
	ClientId     string `json:"clientId"`
	CodeVerifier string `json:"codeVerifier,optional"`
}

type OpenapiCreateResult struct {
	Success bool             `json:"success"`
	Topic   string           `json:"topic"`
	Error   OpenapiItemError `json:"error,optional"`
}

type OpenapiEmptyResp struct {
	Success bool `json:"success"`
}

type OpenapiFlowCreateResp struct {
	Id       int64  `json:"id"`
	BrokerID string `json:"brokerID"`
}

type OpenapiFlowDataResp struct {
	Rev   string        `json:"rev"`
	Flows []interface{} `json:"flows"`
}

type OpenapiFlowDeployResp struct {
	FlowId string `json:"flowId"`
}

type OpenapiFlowEmptyResp struct {
	Success bool `json:"success"`
}

type OpenapiFlowInfo struct {
	Id          int64  `json:"id"`
	FlowId      string `json:"flowId"`
	FlowName    string `json:"flowName"`
	FlowType    string `json:"flowType"`
	FlowStatus  string `json:"flowStatus"`
	Template    string `json:"template"`
	Description string `json:"description"`
	IsFavorite  int64  `json:"isFavorite"`
	CreatedTime int64  `json:"createdTime"`
	UpdatedTime int64  `json:"updatedTime"`
}

type OpenapiFlowLegacyCreateReq struct {
	FlowName    string `json:"flowName"`
	FlowType    string `json:"flowType"`
	Description string `json:"description,optional"`
	Template    string `json:"template,optional"`
}

type OpenapiFlowLegacyDeleteReq struct {
	Ids []int64 `json:"ids"`
}

type OpenapiFlowLegacyDeployReq struct {
	Id        int64  `json:"id"`
	FlowsJson string `json:"flowsJson"`
}

type OpenapiFlowLegacyGetReq struct {
	Id int64 `json:"id"`
}

type OpenapiFlowLegacyListReq struct {
	Keyword  string `json:"keyword,optional"`
	FlowType string `json:"flowType,optional"`
}

type OpenapiFlowLegacyNodesReq struct {
	FlowType string `json:"flowType"`
}

type OpenapiFlowLegacyUpdateReq struct {
	Id          int64  `json:"id"`
	FlowName    string `json:"flowName,optional"`
	Description string `json:"description,optional"`
	Template    string `json:"template,optional"`
	IsFavorite  int64  `json:"isFavorite,optional"`
}

type OpenapiFlowListResp struct {
	List []OpenapiFlowInfo `json:"list"`
}

type OpenapiFlowNodesResp struct {
	Nodes []OpenapiNodeRedNodeSet `json:"nodes"`
}

type OpenapiHistoryItem struct {
	Success bool                 `json:"success"`
	Topic   string               `json:"topic"`
	Result  OpenapiHistoryResult `json:"result,optional"`
	Error   OpenapiItemError     `json:"error,optional"`
}

type OpenapiHistoryResult struct {
	Values []OpenapiHistoryValue `json:"values"`
	Meta   HistoryQueryMeta      `json:"meta,optional"`
}

type OpenapiHistoryValue struct {
	Value     interface{} `json:"value,optional"`
	Quality   string      `json:"quality"`
	TimeStamp int64       `json:"timeStamp"`
}

type OpenapiItemError struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

type OpenapiNodeInfo struct {
	Id               int64             `json:"id"`
	Path             string            `json:"path"`
	Name             string            `json:"name"`
	Type             string            `json:"type"`
	TopicType        string            `json:"topicType"`
	Description      string            `json:"description,optional"`
	DisplayName      string            `json:"displayName,optional"`
	ExtendProperties map[string]string `json:"extendProperties,optional"`
	Fields           []SchemaField     `json:"fields,optional"`
	Children         []OpenapiNodeInfo `json:"children,optional"`
	Alias            string            `json:"alias,optional"`
	EnableHistory    bool              `json:"enableHistory,optional"`
	BindFlowID       int64             `json:"bindFlowID,optional"`
	Payload          OpenapiVQT        `json:"payload,optional"`
}

type OpenapiNodeRedNodeSet struct {
	Id      string   `json:"id"`
	Name    string   `json:"name"`
	Types   []string `json:"types"`
	Enabled bool     `json:"enabled"`
	Module  string   `json:"module"`
	Version string   `json:"version"`
}

type OpenapiReadItem struct {
	Success  bool             `json:"success"`
	Topic    string           `json:"topic"`
	Result   OpenapiVQT       `json:"result,optional"`
	Error    OpenapiItemError `json:"error,optional"`
	Metadata OpenapiNodeInfo  `json:"metadata,optional"`
}

type OpenapiUnsNodeSaveReq struct {
	NodeId           int64         `path:"nodeId,optional"`
	ParentId         int64         `json:"parentId,optional"`
	Name             string        `json:"name"`
	DisplayName      string        `json:"displayName,optional"`
	Alias            string        `json:"alias,optional"`
	Namespace        string        `json:"namespace,optional"`
	NodeType         string        `json:"type,optional"`
	TopicType        string        `json:"topicType,optional"`
	Fields           []SchemaField `json:"fields,optional"`
	Description      string        `json:"description,optional"`
	LabelIds         []int64       `json:"labelIds,optional"`
	AssetFileIds     []int64       `json:"assetFileIds,optional"`
	ExtendProperties string        `json:"extendProperties,optional"`
	EnableHistory    *bool         `json:"enableHistory,optional"`
	WithFlow         bool          `json:"withFlow,optional"`
	AddFlow          bool          `json:"addFlow,optional"`
	MockData         bool          `json:"mockData,optional"`
}

type OpenapiVQT struct {
	Value     interface{} `json:"value,optional"`
	Quality   string      `json:"quality"`
	TimeStamp int64       `json:"timeStamp"`
}

type OpenapiWriteResult struct {
	Success bool             `json:"success"`
	Topic   string           `json:"topic"`
	Error   OpenapiItemError `json:"error,optional"`
}

type PageReq struct {
	PageNo   int    `form:"pageNo,optional"`
	PageSize int    `form:"pageSize,optional"`
	Keyword  string `form:"keyword,optional"`
	KeyType  string `form:"keyType,optional"`
}

type PlatformGetMembersReq struct {
	Keyword        string   `json:"keyword,optional"`
	RoleKey        string   `json:"roleKey,optional"`
	Roles          []string `json:"roles,optional"`
	Statuses       []string `json:"statuses,optional"`
	UpdatedAtStart string   `json:"updatedAtStart,optional"`
	UpdatedAtEnd   string   `json:"updatedAtEnd,optional"`
	Page           int64    `json:"page,optional"`
	Size           int64    `json:"size,optional"`
}

type PlatformMemberResp struct {
	UserId    string                   `json:"userId"`
	UserName  string                   `json:"userName,optional"`
	NickName  string                   `json:"nickName,optional"`
	Email     string                   `json:"email,optional"`
	Status    string                   `json:"status"`
	Roles     []PlatformMemberRoleResp `json:"roles"`
	UpdatedAt string                   `json:"updatedAt"`
}

type PlatformMemberRoleResp struct {
	RoleId      string `json:"roleId"`
	RoleKey     string `json:"roleKey"`
	RoleName    string `json:"roleName,optional"`
	Description string `json:"description,optional"`
}

type PlatformMembersResp struct {
	List  []PlatformMemberResp `json:"list"`
	Total int64                `json:"total"`
	Page  int64                `json:"page"`
	Size  int64                `json:"size"`
}

type ReadReq struct {
	Topics           []string `json:"topics"`
	IncludeMetadata  bool     `json:"include_metadata,optional"`
	IncludeLeafValue bool     `json:"include_leaf_value,optional"`
}

type ReadResp struct {
	Success bool              `json:"success"`
	Results []OpenapiReadItem `json:"results"`
}

type ResourceActionIdReq struct {
	ResourceId int64 `path:"resourceId"`
	ActionId   int64 `path:"actionId"`
}

type ResourceActionSaveReq struct {
	ResourceId  int64  `path:"resourceId"`
	ActionId    int64  `path:"actionId,optional"`
	ActionType  string `json:"actionType"`
	ActionValue string `json:"actionValue"`
	Methods     string `json:"methods,optional"`
	Enabled     int64  `json:"enabled,optional"`
}

type ResourceIdReq struct {
	ResourceId int64 `path:"resourceId"`
}

type ResourceSaveReq struct {
	ResourceId   int64  `path:"resourceId,optional"`
	ParentId     int64  `json:"parentId,optional"`
	ResourceKey  string `json:"resourceKey"`
	Name         string `json:"name"`
	ResourceType int64  `json:"type"`
	RoutePath    string `json:"routePath,optional"`
	UrlType      int64  `json:"urlType,optional"`
	OpenType     int64  `json:"openType,optional"`
	Icon         string `json:"icon,optional"`
	Sort         int64  `json:"sort,optional"`
	Enabled      int64  `json:"enabled,optional"`
}

type RoleResourceReq struct {
	Uri string `json:"uri"`
}

type RoleSaveReq struct {
	Id                int64             `path:"id,optional"`
	Name              string            `json:"name"`
	DefaultHomePage   string            `json:"defaultHomePage,optional"`
	AllowResourceList []RoleResourceReq `json:"allowResourceList,optional"`
	DenyResourceList  []RoleResourceReq `json:"denyResourceList,optional"`
}

type RouteKeyReq struct {
	RouteKey string `path:"routeKey"`
}

type SchemaField struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Unit string `json:"unit,optional"`
}

type SearchReq struct {
	Keyword          string `json:"keyword,optional"`
	TopicType        string `json:"topicType,optional"`
	PathPrefix       string `json:"path_prefix,optional"`
	IncludeMetadata  bool   `json:"include_metadata,optional"`
	IncludeLeafValue bool   `json:"include_leaf_value,optional"`
	Page             int64  `json:"page,optional"`
	Size             int64  `json:"size,optional"`
}

type SearchResp struct {
	Objects []OpenapiNodeInfo `json:"objects"`
	Page    int64             `json:"page"`
	Size    int64             `json:"size"`
	Total   int64             `json:"total"`
}

type UnsAttachmentInfo struct {
	UnsId            int64  `json:"unsId"`
	FileName         string `json:"fileName,optional"`
	FilePath         string `json:"filePath"`
	FileUrl          string `json:"fileUrl,optional"`
	ContentType      string `json:"contentType,optional"`
	Size             int64  `json:"size,optional"`
	Sha256           string `json:"sha256,optional"`
	CreatedAt        int64  `json:"createdAt,optional"`
	FileUrlExpiresAt int64  `json:"fileUrlExpiresAt,optional"`
}

type UnsAttachmentListReq struct {
	UnsId          int64  `json:"unsId,optional"`
	Topic          string `json:"topic,optional"`
	Page           int    `json:"page,optional"`
	Size           int    `json:"size,optional"`
	IncludeFileUrl *bool  `json:"includeFileUrl,optional"`
}

type UnsAttachmentListResp struct {
	UnsId int64               `json:"unsId"`
	List  []UnsAttachmentInfo `json:"list"`
	Total int64               `json:"total"`
	Page  int64               `json:"page"`
	Size  int64               `json:"size"`
}

type UnsAttachmentUploadReq struct {
	UnsId    int64  `json:"unsId,optional"`
	Topic    string `json:"topic,optional"`
	FileName string `json:"fileName,optional"`
	Sha256   string `json:"sha256,optional"`
}

type UnsAttachmentUploadResp struct {
	UnsId            int64  `json:"unsId"`
	FileName         string `json:"fileName,optional"`
	FilePath         string `json:"filePath"`
	FileUrl          string `json:"fileUrl,optional"`
	ContentType      string `json:"contentType,optional"`
	Size             int64  `json:"size,optional"`
	Sha256           string `json:"sha256,optional"`
	CreatedAt        int64  `json:"createdAt,optional"`
	FileUrlExpiresAt int64  `json:"fileUrlExpiresAt,optional"`
}

type UnsBindFlowReq struct {
	UnsId  int64 `json:"unsId"`
	FlowId int64 `json:"flowId"`
}

type UnsBindFlowResp struct {
	Success bool  `json:"success"`
	UnsId   int64 `json:"unsId"`
	FlowId  int64 `json:"flowId"`
}

type UnsDashboardReq struct {
	NodeId    int64 `form:"nodeId"`
	TimeStart int64 `form:"timeStart,optional"`
	TimeEnd   int64 `form:"timeEnd,optional"`
	Limit     int   `form:"limit,optional"`
}

type UnsExportJobReq struct {
	RootNodeId int64 `json:"rootNodeId,optional"`
}

type UnsImportJobReq struct {
	DryRun       bool  `json:"dryRun,optional"`
	SourceFileId int64 `json:"sourceFileId,optional"`
}

type UnsLabelReq struct {
	Id          int64  `path:"id,optional"`
	Name        string `json:"name"`
	Color       string `json:"color,optional"`
	Description string `json:"description,optional"`
}

type UnsListReq struct {
	ParentId       int64  `form:"parentId,optional"`
	ParentIdSet    bool   `form:"parentIdSet,optional"`
	Keyword        string `form:"keyword,optional"`
	IncludeRecycle bool   `form:"includeRecycle,optional"`
}

type UnsNodeSaveReq struct {
	NodeId           int64   `path:"nodeId,optional"`
	ParentId         int64   `json:"parentId,optional"`
	Name             string  `json:"name"`
	DisplayName      string  `json:"displayName,optional"`
	Alias            string  `json:"alias,optional"`
	Namespace        string  `json:"namespace,optional"`
	NodeType         string  `json:"type"`
	TopicType        string  `json:"topicType,optional"`
	Schema           string  `json:"schema,optional"`
	Description      string  `json:"description,optional"`
	LabelIds         []int64 `json:"labelIds,optional"`
	AssetFileIds     []int64 `json:"assetFileIds,optional"`
	ExtendProperties string  `json:"extendProperties,optional"`
	Persistence      *bool   `json:"persistence,optional"`
	WithFlow         bool    `json:"withFlow,optional"`
	AddFlow          bool    `json:"addFlow,optional"`
	MockData         bool    `json:"mockData,optional"`
}

type UserPasswordResetReq struct {
	Id       int64  `path:"id"`
	Password string `json:"password"`
}

type UserRoleReq struct {
	RoleId   int64  `json:"roleId"`
	RoleName string `json:"roleName,optional"`
}

type UserSaveReq struct {
	Username  string        `json:"username"`
	Password  string        `json:"password,optional"`
	FirstName string        `json:"firstName,optional"`
	Email     string        `json:"email,optional"`
	Phone     string        `json:"phone,optional"`
	Enabled   bool          `json:"enabled,optional"`
	RoleList  []UserRoleReq `json:"roleList,optional"`
}

type UserUpdateReq struct {
	Id        int64         `path:"id"`
	Username  string        `json:"username,optional"`
	FirstName string        `json:"firstName,optional"`
	Email     string        `json:"email,optional"`
	Phone     string        `json:"phone,optional"`
	Enabled   bool          `json:"enabled,optional"`
	HomePage  string        `json:"homePage,optional"`
	RoleList  []UserRoleReq `json:"roleList,optional"`
}

type WriteItem struct {
	Topic     string      `json:"topic"`
	Value     interface{} `json:"value,optional"`
	TimeStamp int64       `json:"timeStamp,optional"`
}

type WriteReq struct {
	Writes []WriteItem `json:"writes"`
	Qos    int64       `json:"qos,optional"`
	Retain bool        `json:"retain,optional"`
}

type WriteResp struct {
	Success bool                 `json:"success"`
	Results []OpenapiWriteResult `json:"results"`
}
