// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AdminResetPwdReq struct {
	UserID   string `json:"userId"`
	Password string `json:"password"`
}

type AliasRequest struct {
	Alias string `path:"alias"`
}

type BaseResult struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type BatchCreateReq struct {
	Flags      int               `form:"flags,optional"`
	FromImport bool              `form:"fromImport,optional,default=false"`
	List       []*CreateTopicDto `json:"list"`
}

type BatchQueryFileReq struct {
	AliasList []string `json:"aliasList"`
}

type BatchRemoveUnsDto struct {
	AliasList       []string `json:"aliasList"`
	WithFlow        *bool    `json:"withFlow,optional"`
	WithDashboard   *bool    `json:"withDashboard,optional"`
	RemoveRefer     *bool    `json:"removeRefer,optional"`
	CheckMount      *bool    `json:"checkMount,optional"`
	OnlyRemoveChild *bool    `json:"onlyRemoveChild,optional"`
}

type BatchUpdateResource struct {
	ID              int64   `json:"id,string,optional"` // 同上
	Code            *string `json:"code,optional"`
	Name            *string `json:"name,optional"`
	NameCode        *string `json:"nameCode,optional"`
	DescriptionCode *string `json:"descriptionCode,optional"`
	ParentID        *int64  `json:"parentId,string,optional"` // 如有需要
	Type            *int    `json:"type,optional"`
	Source          *string `json:"source,optional"`
	RouteSource     *int    `json:"routeSource,optional"`
	URL             *string `json:"url,optional"`
	URLType         *int    `json:"urlType,optional"`
	OpenType        *int    `json:"openType,optional"`
	Icon            *string `json:"icon,optional"`
	Description     *string `json:"description,optional"`
	Sort            *int    `json:"sort,optional"`
	EditEnable      *bool   `json:"editEnable,optional"`
	HomeEnable      *bool   `json:"homeEnable,optional"`
	Fixed           *bool   `json:"fixed,optional"`
	Enable          *bool   `json:"enable,optional"`
}

type BatchUpdateResourceReq struct {
	Items []BatchUpdateResource
}

type CancelLabelReq struct {
	UnsId    int64   `form:"unsId"`
	LabelIds []int64 `json:"labelIds"`
}

type CheckDuplicationNameReq struct {
	Folder    string `form:"folder,optional"`
	Name      string `form:"name"`
	CheckType int    `form:"checkType"`
}

type CommonResp struct {
	ID int64 `json:"id,optional"` // id
}

type Compare struct {
	CmpTYpe string `json:"cmpType"` //"=":相等 "!=":不相等 ">":大于">=":大于等于"<":小于"<=":小于等于 "like":模糊查询,只有string类型可以使用
	Value   string `json:"value"`
	CastTo  string `json:"castTo"` //参数的类型(填写了会进行数据类型的转换): int float string
}

type CompareInt64 struct {
	CmpTYpe string `json:"cmpType"` //"=":相等 "!=":不相等 ">":大于">=":大于等于"<":小于"<=":小于等于 "like":模糊查询
	Value   int64  `json:"value,string"`
}

type CompareString struct {
	CmpTYpe string `json:"cmpType"` //"=":相等 "!=":不相等 ">":大于">=":大于等于"<":小于"<=":小于等于 "like":模糊查询
	Value   string `json:"value"`
}

type ContainerInfo struct {
	Name        string                 `json:"name,optional"`
	Version     string                 `json:"version,optional"`
	Description string                 `json:"description,optional"`
	EnvMap      map[string]interface{} `json:"envMap,optional"`
}

type CreateFileDto struct {
	Name             string                 `json:"name"`
	Alias            string                 `json:"alias,optional"`
	DisplayName      string                 `json:"displayName,optional"`
	ParentAlias      string                 `json:"parentAlias,optional"`
	DataType         int                    `json:"dataType,optional"`
	Description      string                 `json:"description,optional"`
	Definition       []FieldDefine          `json:"definition,optional"`
	Persistence      bool                   `json:"persistence,optional"`
	DashBoard        bool                   `json:"dashBoard,optional"`
	AddFlow          bool                   `json:"addFlow,optional"`
	Refers           []InstanceField        `json:"refers,optional"`
	Expression       string                 `json:"expression,optional"`
	Frequency        string                 `json:"frequency,optional"`
	ExtendProperties map[string]interface{} `json:"extendProperties,optional"`
	TemplateAlias    string                 `json:"templateAlias,optional"`
	LabelNames       []string               `json:"labelNames,optional"`
}

type CreateLabelReq struct {
	Name string `form:"name"`
}

type CreateLabelResp struct {
	BaseResult
	Data *LabelVo `json:"data"`
}

type CreateTemplateReq struct {
	Batch       int            `json:"batch,optional" swaggerignore:"true"`
	Index       int            `json:"index,optional" swaggerignore:"true"`
	FlagNo      string         `json:"flagNo,optional" swaggerignore:"true"`
	Name        string         `json:"name" validate:"required,max=63"`
	Alias       string         `json:"alias,optional" validate:"omitempty,max=63,alias"`
	Fields      []*FieldDefine `json:"fields" validate:"required,min=1"`
	Description string         `json:"description,optional" validate:"omitempty,max=255"`
}

type CreateTemplateResp struct {
	BaseResult
	Id string `json:"data,optional,omitempty"`
}

type CreateTopicDto struct {
	Id                            int64                     `json:"id,string,optional,omitzero"`
	Batch                         int                       `json:"-"`
	Index                         int                       `json:"-"`
	FlagNo                        string                    `json:"-"`
	Name                          string                    `json:"name" validate:"required,max=63"`
	DisplayName                   *string                   `json:"displayName,optional,omitempty" validate:"max=128"`
	PathType                      int16                     `json:"pathType" validate:"required,min=0,max=2"`
	Path                          string                    `json:"path,optional,omitzero"`
	Alias                         string                    `json:"alias" validate:"required"`
	Description                   string                    `json:"description,optional,omitzero" validate:"max=255"`
	ModelId                       *int64                    `json:"modelId,string,optional,omitempty"`
	ModelAlias                    *string                   `json:"modelAlias,optional,omitempty"`
	Template                      string                    `json:"-"`
	ParentAlias                   *string                   `json:"parentAlias,optional,omitempty"`
	ParentId                      *int64                    `json:"parentId,string,optional,omitempty"`
	DataType                      *int16                    `json:"dataType,optional,string,omitempty" validate:"min=1,max=7"` // Data type and fields
	ParentDataType                *int16                    `json:"parentDataType,optional,string,omitempty"`
	Fields                        []*FieldDefine            `json:"fields,optional"`
	DataSrcID                     int16                     `json:"-"`
	TableName                     string                    `json:"-"` // Table fields
	TbFieldName                   string                    `json:"-"`
	PrimaryField                  []string                  `json:"-"`
	HasBlobField                  bool                      `json:"-"`
	ReferUns                      string                    `json:"referUns,optional,omitzero"` // Reference fields
	ReferIds                      []int64                   `json:"referIds,optional,omitzero"`
	RefUns                        map[int64]int             `json:"refUns,optional"`
	LayRec                        string                    `json:"-"`
	ReferTable                    string                    `json:"referTable,optional,omitzero"`
	RefFields                     []*FieldDefine            `json:"refFields,optional,omitzero"`
	ReferModelID                  string                    `json:"referModelId,optional,omitzero"`
	Cited                         map[int64]bool            `json:"-"`                        // Set of cited IDs
	Refers                        []*InstanceField          `json:"refers,optional,omitzero"` // Calculation fields
	Expression                    string                    `json:"expression,optional,omitzero" validate:"max=255"`
	CompileExpression             interface{}               `json:"-"`
	StreamOptions                 *StreamOptions            `json:"streamOptions,optional,omitzero"`
	DataPath                      string                    `json:"dataPath,optional"`
	Protocol                      map[string]interface{}    `json:"protocol,optional"`
	ProtocolType                  string                    `json:"protocolType,optional"`
	ProtocolBean                  interface{}               `json:"-"`
	WithFlags                     *int32                    `json:"withFlags,optional,string,omitempty"` // Flags and options
	AddFlow                       *bool                     `json:"addFlow,optional,string,omitempty"`
	AddDashBoard                  *bool                     `json:"addDashBoard,optional,string,omitempty"`
	Save2Db                       *bool                     `json:"save2db,optional,string",omitempty`
	RetainTableWhenDeleteInstance *bool                     `json:"retainTableWhenDeleteInstance,optional,string,omitempty"`
	CreateTemplate                *bool                     `json:"createTemplate,optional,string,omitempty"`
	SubscribeEnable               *bool                     `json:"subscribeEnable,optional,string,omitempty"`
	Frequency                     string                    `json:"frequency,optional,omitzero"` // Frequency for merge type
	FrequencySeconds              *int64                    `json:"-"`
	AlarmRuleDefine               interface{}               `json:"-"`                                         // AlarmRuleDefine type
	Extend                        map[string]interface{}    `json:"extend,optional,omitzero" validate:"max=3"` // Extended fields
	ExtendFieldUsed               []string                  `json:"extendFieldUsed,optional,omitzero"`
	LabelNames                    []string                  `json:"labelNames,optional,omitzero"`
	LabelIDs                      map[int64]string          `json:"-"`
	Order                         int                       `json:"-"`
	RefSource                     string                    `json:"refSource,optional,omitzero"` // Pride specific fields
	ValueType                     string                    `json:"valueType,optional,omitzero"`
	InitValue                     interface{}               `json:"initValue,optional,omitzero"`
	StrMaxLen                     int                       `json:"strMaxLen,optional,omitzero"`
	AccessLevel                   string                    `json:"accessLevel,optional,omitzero"`       // Access level
	MountType                     *int16                    `json:"mountType,optional,omitempty,string"` // Mount fields
	MountSource                   string                    `json:"mountSource,optional,omitzero"`
	UpdateAt                      int64                     `json:"updateAt,optional,omitzero"` // Update metadata
	CreateAt                      int64                     `json:"createAt,optional,omitzero"`
	FieldsChanged                 bool                      `json:"-"`
	TmField                       string                    `json:"-"` // Internal fields
	FieldDefines                  *FieldDefines             `json:"-"`
	RefTopicFields                map[int64]map[string]bool `json:"-"`
	Status                        int16                     `json:"-"`
	CountExistsSiblings           int64                     `json:"-"`
}

type CreateUnsNodeRedDto struct {
	Path      string `json:"path"`
	Alias     string `json:"alias,optional"`
	FieldType string `json:"fieldType,optional"`
	FieldName string `json:"fieldName,optional"`
	Tag       string `json:"tag,optional"`
}

type DashboardDto struct {
	ID          string `json:"id,omitzero"`
	Name        string `json:"name"`
	Type        int    `json:"type"` // 1-grafana 2-fuxa
	NeedInit    bool   `json:"needInit"`
	Description string `json:"description,omitzero"`
	JsonContent string `json:"jsonContent,omitzero"`
	Creator     string `json:"creator,omitzero"`
	UpdateTime  string `json:"updateTime,omitzero"`
	CreateTime  string `json:"createTime,omitzero"`
}

type DashboardPageResp struct {
	PageResultDTO
	Data []DashboardDto `json:"data"`
}

type DashboardRefDto struct {
	DashboardID string `json:"dashboardId"`
	UnsAlias    string `json:"unsAlias"`
}

type DateRange struct {
	Start string `json:"start,optional"` //开始时间 格式：yyyy-mm-dd
	End   string `json:"end,optional"`   //结束时间 格式：yyyy-mm-dd
}

type DbFieldDefineVo struct {
	Name       string `json:"name"`
	Type       string `json:"type"`
	Length     int    `json:"length"`
	IsNullable bool   `json:"isNullable"`
	Comment    string `json:"comment"`
}

type DbFieldsInfoVo struct {
	DatabaseType string            `json:"databaseType"`
	Fields       []DbFieldDefineVo `json:"fields"`
}

type DbFieldsInfoVoResp struct {
	BaseResult
	Data []FieldDefine `json:"data"`
}

type DetailRequest struct {
	ID string `form:"id"`
}

type DetectRemoveReq struct {
	Id int64 `form:"id"`
}

type EmailUpdateReq struct {
	Email string `form:"email"`
}

type Empty struct {
}

type EmptyFolderReq struct {
}

type EmptyFolderResp struct {
	BaseResult
	Data []*CreateTopicDto `json:"data"`
}

type EventFlowCopyReq struct {
	SourceID    string `json:"sourceId"`
	FlowName    string `json:"flowName"`
	Description string `json:"description,optional"`
	Template    string `json:"template,optional"`
}

type EventFlowCreateReq struct {
	FlowName    string `json:"flowName"`
	Description string `json:"description,optional"`
	Template    string `json:"template,optional"`
}

type EventFlowDeleteReq struct {
	ID string `form:"id"`
}

type EventFlowDeployReq struct {
	ID    string                   `json:"id"`
	Flows []map[string]interface{} `json:"flows,optional"`
}

type EventFlowInfo struct {
	ID          string `json:"id,optional"`
	FlowName    string `json:"flowName,optional"`
	FlowID      string `json:"flowId,optional"`
	Description string `json:"description,optional"`
	FlowStatus  string `json:"flowStatus,optional"`
	Template    string `json:"template,optional"`
	Mark        int    `json:"mark,optional"`
	Creator     string `json:"creator,optional"`
	CreateTime  int    `json:"createTime,optional"`
}

type EventFlowListQuery struct {
	Keyword   string `form:"k,optional"`
	OrderCode string `form:"orderCode,optional"`
	IsAsc     string `form:"isAsc,optional"`
	PageNo    int64  `form:"pageNo,optional,default=1"`
	PageSize  int64  `form:"pageSize,optional,default=10"`
}

type EventFlowPageResult struct {
	Code     int             `json:"code"`
	Msg      string          `json:"msg,optional"`
	PageNo   int64           `json:"pageNo"`
	PageSize int64           `json:"pageSize"`
	Total    int64           `json:"total"`
	Data     []EventFlowInfo `json:"data,optional"`
}

type EventFlowSaveReq struct {
	ID    string                   `json:"id"`
	Flows []map[string]interface{} `json:"flows,optional"`
}

type EventFlowUpdateReq struct {
	ID          string `json:"id"`
	FlowName    string `json:"flowName"`
	Description string `json:"description,optional"`
}

type Field struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type FieldDef struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Unique      bool   `json:"unique,optional"`
	Index       string `json:"index,optional"`
	DisplayName string `json:"displayName,optional"`
	Remark      string `json:"remark,optional"`
	MaxLen      int64  `json:"maxLen,optional"`
	TbValueName string `json:"tbValueName,optional"`
}

type FieldDefine struct {
	Name        string   `json:"name"`
	Type        string   `json:"type"`
	Unique      *bool    `json:"unique,optional,omitempty"`
	Index       *string  `json:"index,optional,omitempty"`
	DisplayName *string  `json:"displayName,optional,omitempty"`
	Remark      *string  `json:"remark,optional,omitempty"`
	MaxLen      *int     `json:"maxLen,optional,omitempty"`
	TbValueName *string  `json:"tbValueName,optional,omitempty"`
	Unit        *string  `json:"unit,optional,omitempty"`
	UpperLimit  *float64 `json:"upperLimit,optional,omitempty"`
	LowerLimit  *float64 `json:"lowerLimit,optional,omitempty"`
	Decimal     *int     `json:"decimal,optional,omitempty"`
}

type FieldDefines struct {
	FieldsMap     map[string]*FieldDefine // Field name -> FieldDefine  // Field name -> FieldDefine
	FieldIndexMap map[string]string       // Index -> Field name  // Index -> Field name
	UniqueKeys    map[string]bool         // Set of unique field names  // Set of unique field names
	CalcField     *FieldDefine            // Calculation field  // Calculation field
}

type FileVo struct {
	UnsId    string `json:"unsId"`
	Name     string `json:"name"`
	Path     string `json:"path"`
	PathType int16  `json:"pathType"`
}

type FlowMarkReq struct {
	ID string `json:"id,optional"`
}

type FlowUNMarkReq struct {
	ID string `form:"id,optional"`
}

type GetByUnsRequest struct {
	UnsAlias string `form:"unsAlias"`
}

type GetLastMsgReq struct {
	Paths []string `form:"path,optional"`
	Id    int64    `form:"id,optional"`
	Alias string   `form:"alias,optional"`
}

type GetLastMsgResp struct {
	BaseResult
	Data map[string]interface{} `json:"data"`
}

type HistoryValueRequest struct {
}

type HomePageReq struct {
	HomePage string `form:"homePage"`
}

type IDList struct {
	IDs []int64 `json:"ids"`
}

type InstanceDetail struct {
	Id               string                 `json:"id"`
	Topic            string                 `json:"topic"`
	Alias            string                 `json:"alias"`
	ParentAlias      *string                `json:"parentAlias"`
	Path             string                 `json:"path"`
	DataType         *int16                 `json:"dataType"`
	ParentDataType   *int16                 `json:"parentDataType"`
	DataPath         *string                `json:"dataPath"`
	PathType         int16                  `json:"pathType"`
	Fields           []*FieldDefine         `json:"fields"`
	CreateTime       int64                  `json:"createTime"`
	UpdateTime       int64                  `json:"updateTime"`
	Protocol         map[string]interface{} `json:"protocol"`
	ModelDescription string                 `json:"modelDescription"`
	Description      string                 `json:"description"`
	WithFlow         bool                   `json:"withFlow"`
	WithDashboard    bool                   `json:"withDashboard"`
	WithSave2db      bool                   `json:"withSave2db"`
	Save2db          bool                   `json:"save2db"`
	SubscribeEnable  bool                   `json:"subscribeEnable"`
	Expression       string                 `json:"expression"`
	ShowExpression   string                 `json:"showExpression"`
	Refers           []InstanceField        `json:"refers"`
	LabelList        []LabelVo              `json:"labelList"`
	Name             string                 `json:"name"`
	DisplayName      string                 `json:"displayName"`
	PathName         string                 `json:"pathName"`
	ModelId          string                 `json:"modelId"`
	ModelName        string                 `json:"modelName"`
	Extend           map[string]interface{} `json:"extend"`
	Payload          string                 `json:"payload"`
	TemplateName     string                 `json:"templateName"`
	TemplateAlias    string                 `json:"templateAlias"`
	AccessLevel      string                 `json:"accessLevel"`
	Mount            *MountDetailVo         `json:"mount"`
}

type InstanceDetailReq struct {
	Id int64 `form:"id"`
}

type InstanceDetailResp struct {
	BaseResult
	Data *InstanceDetail `json:"data"`
}

type InstanceField struct {
	Id    int64  `json:"id"`
	Alias string `json:"alias"`
	Path  string `json:"path"`
	Topic string `json:"path"`
	Field string `json:"field"`
	Uts   bool   `json:"uts"`
}

type IsExistRequest struct {
	Alias string `form:"alias"`
}

type JsonBodyReq struct {
	Json string `json:"json"`
}

type JsonResult struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg,omitzero"`
	Data interface{} `json:"data,omitzero"`
}

type LabelDetailResult struct {
	BaseResult
	Data *LabelVo `json:"data"`
}

type LabelPageReq struct {
	LabelId  int64 `form:"labelId"`
	PageNo   int64 `form:"pageNo,optional,default=1"`
	PageSize int64 `form:"pageSize,optional,default=20"`
}

type LabelVo struct {
	ID                 int64  `json:"id,string"`
	LabelName          string `json:"labelName,omitempty"`
	CreateAt           int64  `json:"createAt,omitzero"`
	Topic              string `json:"topic,omitempty"`
	SubscribeEnable    *bool  `json:"subscribeEnable,omitempty"`
	SubscribeFrequency string `json:"subscribeFrequency,omitempty"`
	CreateTime         int64  `json:"createTime,omitzero"`
	SubscribeAt        int64  `json:"subscribeAt,omitzero"`
}

type ListTypesResult struct {
	BaseResult
	Data []string `json:"data"`
}

type MakeLabelReq struct {
	UnsId     int64      `form:"unsId"`
	LabelList []*LabelVo `json:"labelList,optional"`
}

type MakeSingleLabelReq struct {
	UnsId   int64 `form:"unsId"`
	LabelId int64 `form:"labelId"`
}

type MarkTopRequest struct {
	ID string `json:"id"`
}

type ModelDetail struct {
	Id                 string                 `json:"id"`
	Topic              string                 `json:"topic"`
	SubscribeEnable    bool                   `json:"subscribeEnable"`
	SubscribeFrequency string                 `json:"subscribeFrequency"`
	Alias              string                 `json:"alias"`
	ParentAlias        string                 `json:"parentAlias"`
	Path               string                 `json:"path"`
	DataType           int                    `json:"dataType"`
	Fields             []*FieldDefine         `json:"fields"`
	CreateTime         int64                  `json:"createTime"`
	UpdateTime         int64                  `json:"updateTime"`
	Description        string                 `json:"description"`
	Name               string                 `json:"name"`
	DisplayName        string                 `json:"displayName"`
	PathName           string                 `json:"pathName"`
	ModelId            string                 `json:"modelId"`
	ModelName          string                 `json:"modelName"`
	Extend             map[string]interface{} `json:"extend"`
	TemplateAlias      string                 `json:"templateAlias"`
	Mount              *MountDetailVo         `json:"mount"`
}

type ModelDetailReq struct {
	Id int64 `form:"id"`
}

type ModelDetailResp struct {
	BaseResult
	Data *ModelDetail `json:"data"`
}

type MountDetailVo struct {
	MountType   *int16 `json:"mountType,omitempty,string"`
	MountSource string `json:"mountSource,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
}

type OperationResult struct {
	Success bool `json:"success"`
}

type OrderBy struct {
	Field string `json:"field,optional"` ////排序的字段名
	Sort  int64  `json:"sort,optional"`  //排序方式：0 从小到大, 1 从大到小
}

type OuterStructureVo struct {
	DataPath string        `json:"dataPath"`
	Fields   []FieldDefine `json:"fields"`
}

type PageInfo struct {
	Page   int64      `json:"page,optional" form:"page,optional"` // 页码
	Size   int64      `json:"size,optional" form:"size,optional"` // 每页大小
	Orders []*OrderBy `json:"orders,optional"`                    //排序
}

type PageListRequest struct {
	K         string `form:"k,optional"`         // 关键字
	Type      int    `form:"type,optional"`      // Dashboard 类型
	OrderCode string `form:"orderCode,optional"` // 排序字段
	IsAsc     string `form:"isAsc,optional"`     // 是否升序
	PageNum   int    `form:"pageNum,default=1"`
	PageSize  int    `form:"pageSize,default=10"`
}

type PageListUnsByTemplateReq struct {
	ID       int64 `form:"templateId,string" json:"id,string"`
	PageNo   int64 `form:"pageNo,optional,default=1" json:"pageNo,optional,default=1" `       // 当前页数，默认为1
	PageSize int64 `form:"pageSize,optional,default=20" json:"pageSize,optional,default=20" ` // 每页记录数，默认为20，最大支持1000
}

type PageListUnsByTemplateResp struct {
	PageResultDTO
	Data []*FileVo `json:"data,optional,omitempty"`
}

type PageResp struct {
	Page     int64 `json:"page,optional"`     // 页码
	PageSize int64 `json:"pageSize,optional"` // 每页大小
	Total    int64 `json:"total"`
}

type PageResultDTO struct {
	PageNo   int64  `json:"pageNo"`
	PageSize int64  `json:"pageSize"`
	Total    int64  `json:"total"`
	Code     int64  `json:"code"`
	Msg      string `json:"msg,omitempty"`
}

type PaginationDTO struct {
	PageNo   int64 `json:"pageNo,default=1" form:"pageNo,default=1"`       // 当前页数，默认为1
	PageSize int64 `json:"pageSize,default=20" form:"pageSize,default=20"` // 每页记录数，默认为20，最大支持1000
}

type ParseJson2TreeUnsResp struct {
	BaseResult
	Data []TreeOuterStructureVo `json:"data"`
}

type ParseJson2UnsResp struct {
	BaseResult
	Data []OuterStructureVo `json:"data"`
}

type ParserTopicPayloadReq struct {
	Topic string `form:"topic"`
}

type PasteRequestVO struct {
	SourceId int64 `json:"sourceId"`
	TargetId int64 `json:"targetId"`
	NewF     bool  `json:"newF"`
}

type PhoneUpdateReq struct {
	Phone string `form:"phone"`
}

type Point struct {
	Longitude float64 `json:"longitude,range=[0:180]"` //经度
	Latitude  float64 `json:"latitude,range=[0:90]"`   //纬度
}

type RemoveReq struct {
	Id            int64 `form:"id"`
	WithFlow      *bool `form:"withFlow,default=true"`
	WithDashboard *bool `form:"withDashboard,default=true"`
	RemoveRefer   *bool `form:"cascade,optional"`
}

type RemoveResult struct {
	BaseResult
	Data *RemoveTip `json:"data,omitempty"`
}

type RemoveTip struct {
	Refs int `json:"refs"`
}

type ResourceBatchDeleteReq struct {
	IDs []int64 `json:"ids"` // 注意：如果前端传 ["1","2"] 这种字符串数组，这里不能用 ,string；见下方说明
}

type ResourceIDReq struct {
	ID int64 `path:"id"`
}

type ResourceInfo struct {
	PolicyID   string   `json:"policyId,optional"`
	ResourceID string   `json:"resourceId,optional"`
	URI        string   `json:"uri"`
	Methods    []string `json:"methods,optional"`
}

type ResourceQuery struct {
	ParentID int64 `form:"parentId,optional"`
	Type     int   `form:"type,optional"`
}

type ResourceVO struct {
	ID              string `json:"id,optional"`
	ParentID        string `json:"parentId,optional"`
	Type            int    `json:"type,optional"`
	Code            string `json:"code,optional"`
	NameCode        string `json:"nameCode,optional"`
	ShowName        string `json:"showName,optional"`
	RouteSource     int    `json:"routeSource,optional"`
	URL             string `json:"url,optional"`
	URLType         int    `json:"urlType,optional"`
	OpenType        int    `json:"openType,optional"`
	Icon            string `json:"icon,optional"`
	DescriptionCode string `json:"descriptionCode,optional"`
	ShowDescription string `json:"showDescription,optional"`
	Sort            int    `json:"sort,optional"`
	EditEnable      bool   `json:"editEnable,optional"`
	HomeEnable      bool   `json:"homeEnable,optional"`
	Fixed           bool   `json:"fixed,optional"`
	Enable          bool   `json:"enable,optional"`
	UpdateAt        string `json:"updateAt,optional"`
	CreateAt        string `json:"createAt,optional"`
}

type ResultVO struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,optional"`
}

type RoleDetail struct {
	RoleID           string         `json:"roleId"`
	RoleName         string         `json:"roleName"`
	ResourceList     []RoleResource `json:"resourceList,optional"`
	DenyResourceList []RoleResource `json:"denyResourceList,optional"`
}

type RoleIDPathReq struct {
	ID string `path:"id"`
}

type RoleInfo struct {
	RoleID          string `json:"roleId"`
	RoleName        string `json:"roleName"`
	RoleDescription string `json:"roleDescription,optional"`
	ClientRole      bool   `json:"clientRole,optional"`
}

type RoleResource struct {
	PolicyID   string   `json:"policyId,optional"`
	ResourceID string   `json:"resourceId,optional"`
	URI        string   `json:"uri"`
	Methods    []string `json:"methods,optional"`
}

type RoleSaveReq struct {
	ID                string         `json:"id,optional"`
	Name              string         `json:"name"`
	AllowResourceList []RoleResource `json:"allowResourceList,optional"`
	DenyResourceList  []RoleResource `json:"denyResourceList,optional"`
}

type RoleSummary struct {
	RoleID          string `json:"roleId"`
	RoleName        string `json:"roleName"`
	RoleDescription string `json:"roleDescription,optional"`
	ClientRole      bool   `json:"clientRole,optional"`
}

type RouteListResp struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data []SimpleRouteVO `json:"data"`
}

type SaveMenuReq struct {
	ServiceName string `form:"serviceName,optional"` // 服务名（可选）
	Name        string `form:"name"`                 // 名称，唯一标识一个菜单
	ShowName    string `form:"showName"`             // 显示名
	Description string `form:"description,optional"` // 描述（可选）
	BaseUrl     string `form:"baseUrl"`              // baseURL
	OpenType    int    `form:"openType"`             // 跳转方式：0-iframe打开，1-打开新页面，2-app
}

type SaveResourceReq struct {
	ID          int64             `json:"id,string,optional"` // 关键：允许 "123" 绑定到 int64
	Code        string            `json:"code,optional"`
	Name        string            `json:"name,optional"`
	ParentID    int64             `json:"parentId,string,optional"` // 如果前端也把 parentId 当字符串传，建议一并加上
	Type        int               `json:"type,optional"`
	Source      string            `json:"source,optional"`
	RouteSource int               `json:"routeSource,optional"`
	URL         string            `json:"url,optional"`
	URLType     int               `json:"urlType,optional"`
	OpenType    int               `json:"openType,optional"`
	Icon        string            `json:"icon,optional"`
	Description string            `json:"description,optional"`
	Sort        int               `json:"sort,optional"`
	EditEnable  bool              `json:"editEnable,optional"`
	HomeEnable  bool              `json:"homeEnable,optional"`
	Fixed       bool              `json:"fixed,optional"`
	Enable      bool              `json:"enable,optional"`
	Children    []SaveResourceReq `json:"children,optional"`
}

type SearchPagedReq struct {
	Key              string  `form:"k,optional"`
	ModelTopic       string  `form:"modelTopic,optional"`
	SearchType       int     `form:"type,optional,default=2"`
	Normal           bool    `form:"normal,optional"`
	DataTypes        []int16 `form:"dataTypes,optional"`
	PageNo           int     `form:"pageNo,optional,default=1"`
	PageSize         int     `form:"pageSize,optional,default=10"`
	NumberFieldCount int     `form:"nfc,optional"`
}

type SearchTreeReq struct {
	Keyword    string `form:"key,optional"`
	ParentId   int64  `form:"parentId,optional,default=-1"`
	ShowRec    bool   `form:"showRec,optional,default=false"`
	SearchType int    `form:"type,optional,default=1"`
	PathType   int16  `form:"pathType,optional,default=-1"`
}

type SearchTreeResp struct {
	BaseResult
	Data []*TopicTreeResult `json:"data,omitempty,optional"`
}

type SendOption struct {
	TimeoutToFail  int64 `json:"timeoutToFail,optional"`  //超时失败时间
	RequestTimeout int64 `json:"requestTimeout,optional"` //请求超时,超时后会进行重试
	RetryInterval  int64 `json:"retryInterval,optional"`  //重试间隔
}

type SimpleRouteVO struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}

type SourceFlowAliasQuery struct {
	Alias string `form:"alias"`
}

type SourceFlowBatchAliasReq struct {
	Aliases []string `json:"aliases"`
}

type SourceFlowCopyReq struct {
	SourceID    string `json:"sourceId"`
	FlowName    string `json:"flowName"`
	Description string `json:"description,optional"`
	Template    string `json:"template,optional"`
}

type SourceFlowCreateReq struct {
	FlowName    string `json:"flowName"`
	Description string `json:"description,optional"`
	Template    string `json:"template,optional"`
}

type SourceFlowDeleteReq struct {
	ID string `form:"id"`
}

type SourceFlowDeployReq struct {
	ID    string                   `json:"id"`
	Flows []map[string]interface{} `json:"flows,optional"`
}

type SourceFlowDeployResult struct {
	FlowID  string `json:"flowId,optional"`
	Version string `json:"version,optional"`
}

type SourceFlowInfo struct {
	ID          string `json:"id,optional"`
	FlowName    string `json:"flowName,optional"`
	FlowID      string `json:"flowId,optional"`
	Description string `json:"description,optional"`
	FlowStatus  string `json:"flowStatus,optional"`
	Template    string `json:"template,optional"`
	Mark        int    `json:"mark,optional"`
	Creator     string `json:"creator,optional"`
	CreateTime  int    `json:"createTime,optional"`
}

type SourceFlowListQuery struct {
	Keyword   string `form:"k,optional"`
	OrderCode string `form:"orderCode,optional"`
	IsAsc     string `form:"isAsc,optional"`
	PageNo    int64  `form:"pageNo,optional,default=1"`
	PageSize  int64  `form:"pageSize,optional,default=10"`
}

type SourceFlowListResult struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg,optional"`
	Data []SourceFlowInfo `json:"data,optional"`
}

type SourceFlowMockReq struct {
	UnsAlias string `json:"unsAlias"`
	Path     string `json:"path"`
}

type SourceFlowPageResult struct {
	Code     int              `json:"code"`
	PageNo   int64            `json:"pageNo"`
	PageSize int64            `json:"pageSize"`
	Total    int64            `json:"total"`
	Data     []SourceFlowInfo `json:"data,optional"`
}

type SourceFlowSaveReq struct {
	ID    string                   `json:"id"`
	Flows []map[string]interface{} `json:"flows,optional"`
}

type SourceFlowUpdateReq struct {
	ID          string `json:"id"`
	FlowName    string `json:"flowName"`
	Description string `json:"description,optional"`
}

type StreamOptions struct {
}

type StringResult struct {
	BaseResult
	Data string `json:"data,optional"`
}

type SubscribeModelReq struct {
	Id        int64  `form:"id"`
	Enable    bool   `form:"enable"`
	Frequency string `form:"frequency,optional"`
}

type SystemConfigResp struct {
	AppTitle             string                   `json:"appTitle,optional"`
	Version              string                   `json:"version,optional"`
	Lang                 string                   `json:"lang,optional"`
	AuthEnable           bool                     `json:"authEnable,optional"`
	LlmType              string                   `json:"llmType,optional"`
	MqttTcpPort          int64                    `json:"mqttTcpPort,optional"`
	MqttWebsocketTslPort int64                    `json:"mqttWebsocketTslPort,optional"`
	LoginPath            string                   `json:"loginPath,optional"`
	PlatformType         string                   `json:"platformType,optional"`
	EntranceUrl          string                   `json:"entranceUrl,optional"`
	MultipleTopic        bool                     `json:"multipleTopic,optional"`
	UseAliasPathAsTopic  bool                     `json:"useAliasPathAsTopic,optional"`
	ContainerMap         map[string]ContainerInfo `json:"containerMap,optional"`
	QualityName          string                   `json:"qualityName,optional"`
	TimestampName        string                   `json:"timestampName,optional"`
	LazyTree             bool                     `json:"lazyTree,optional"`
	LdapEnable           bool                     `json:"ldapEnable,optional"`
}

type Tag struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TemplateDetailResp struct {
	BaseResult
	Data *TemplateVo `json:"data,optional,omitempty"`
}

type TemplatePageResp struct {
	PageResultDTO
	Data []*TemplateSearchResult `json:"data,optional,omitempty"`
}

type TemplateQueryVo struct {
	PaginationDTO
	Key             string `json:"key" schema:"关键字查询，模版名称模糊匹配"`
	SubscribeEnable *bool  `json:"subscribeEnable" schema:"是否订阅"`
}

type TemplateSearchResult struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Alias       string `json:"alias,optional"`
}

type TemplateVo struct {
	ID                 string         `json:"id"`
	Name               string         `json:"name"`
	Alias              string         `json:"alias,optional"`
	Fields             []*FieldDefine `json:"fields,optional,omitempty"`
	CreateTime         int64          `json:"createTime,optional,omitzero"`
	Description        string         `json:"description,optional,omitempty"`
	Topic              string         `json:"topic,optional,omitempty"`
	SubscribeEnable    *bool          `json:"subscribeEnable,optional,omitempty"`
	SubscribeFrequency string         `json:"subscribeFrequency,optional,omitempty"`
}

type TimeRange struct {
	Start int64 `json:"start,optional"` //开始时间 unix时间戳
	End   int64 `json:"end,optional"`   //结束时间 unix时间戳
}

type TipsEnableReq struct {
	TipsEnable int `form:"tipsEnable"`
}

type TokenCallbackReq struct {
	Code string `form:"code"`
}

type TopicInfo struct {
	Id             string         `json:"id"`
	Alias          string         `json:"alias"`
	ParentId       string         `json:"parentId"`
	Name           string         `json:"name"`
	Path           string         `json:"path"`
	Topic          string         `json:"topic"`
	DataType       int            `json:"dataType"`
	ParentDataType *int16         `json:"parentDataType"`
	PathType       int            `json:"pathType"`
	Fields         []*FieldDefine `json:"fields"`
}

type TopicPaginationSearchResult struct {
	Code     int         `json:"code"`
	Msg      string      `json:"msg"`
	PageNo   int64       `json:"pageNo"`
	PageSize int64       `json:"pageSize"`
	Total    int64       `json:"total"`
	Data     []TopicInfo `json:"data"`
}

type TopicTreeResult struct {
	Id             string                 `json:"id"`
	Alias          string                 `json:"alias"`
	ParentId       *string                `json:"parentId,omitempty"`
	ParentAlias    *string                `json:"parentAlias,omitempty"`
	Value          int64                  `json:"value,omitempty"`
	LastUpdateTime int64                  `json:"lastUpdateTime,omitempty"`
	CountChildren  int                    `json:"countChildren,omitempty"`
	PathType       int16                  `json:"pathType"`
	DataType       *int16                 `json:"dataType,omitempty"`
	ParentDataType *int16                 `json:"parentDataType,omitempty"`
	Name           string                 `json:"name"`
	DisplayName    *string                `json:"displayName,omitempty"`
	Path           string                 `json:"path,omitempty"`
	PathName       string                 `json:"pathName,omitempty"`
	Description    string                 `json:"description,omitempty"`
	TemplateAlias  *string                `json:"templateAlias,omitempty"`
	Protocol       string                 `json:"protocol,omitempty"`
	Fields         []*FieldDefine         `json:"fields,omitempty"`
	Children       []*TopicTreeResult     `json:"children,omitempty"`
	Extend         map[string]interface{} `json:"extend,omitempty"`
	HasChildren    bool                   `json:"hasChildren"`
	CreateAt       int64                  `json:"createAt,omitempty"`
	UpdateAt       int64                  `json:"updateAt,omitempty"`
	Mount          *MountDetailVo         `json:"mount,omitempty"`
}

type TreeOuterStructureVo struct {
	Name     string                 `json:"name"`
	DataPath string                 `json:"dataPath"`
	Fields   []FieldDefine          `json:"fields"`
	Children []TreeOuterStructureVo `json:"children"`
}

type UnmarkRequest struct {
	ID string `form:"id"`
}

type UnsByLabelPageResp struct {
	BaseResult
	PageNo   int64    `json:"pageNo"`
	PageSize int64    `json:"pageSize"`
	Total    int64    `json:"total"`
	Data     []FileVo `json:"data"`
}

type UnsCreateTopicDTO struct {
	ParentAlias    string                 `json:"parentAlias,optional"`
	ParentID       int64                  `json:"parentId,optional"`
	ModelID        int64                  `json:"modelId,optional"`
	Alias          string                 `json:"alias,optional"`
	Name           string                 `json:"name"`
	PathType       int64                  `json:"pathType"`
	DataType       int64                  `json:"dataType,optional"`
	Fields         []FieldDef             `json:"fields,optional"`
	Description    string                 `json:"description,optional"`
	Protocol       string                 `json:"protocol,optional"`
	ProtocolType   string                 `json:"protocolType,optional"`
	DataSrcId      int64                  `json:"dataSrcId,optional"`
	AddDashBoard   bool                   `json:"addDashBoard,optional"`
	Save2db        bool                   `json:"save2db,optional"`
	AddFlow        bool                   `json:"addFlow,optional"`
	LabelNames     []string               `json:"labelNames,optional"`
	Extend         map[string]interface{} `json:"extend,optional"`
	CreateTemplate bool                   `json:"createTemplate,optional"`
}

type UnsDataResponseVo struct {
	NotExists   []string          `json:"notExists"`
	ErrorFields map[string]string `json:"errorFields"`
}

type UnsHistoryQueryResult struct {
}

type UnsLabelListReq struct {
	Key string `form:"key,optional"`
}

type UnsLabelListResp struct {
	BaseResult
	Data []*LabelVo `json:"data"`
}

type UnsTreeCondition struct {
	PageNo          int    `json:"pageNo,optional,default=1" validate:"min=1"`
	PageSize        int    `json:"pageSize,optional,default=10" validate:"min=1"`
	SearchType      int    `json:"searchType,optional,default=1" validate:"min=1,max=3"`
	Keyword         string `json:"keyword,optional"`
	ParentId        *int64 `json:"parentId,optional,string"`
	DataType        *int   `json:"dataType,optional,string"`
	PathType        *int   `json:"pathType,optional,string"`
	SubscribeEnable *bool  `json:"subscribeEnable,optional,string"`
}

type UnsTreePageResp struct {
	PageResultDTO
	Data []*TopicTreeResult `json:"data,omitempty,optional"`
}

type UpdateFileDTO struct {
	Alias string                 `json:"alias"`
	Data  map[string]interface{} `json:"data"`
}

type UpdateLabelReq struct {
	ID                 int64  `json:"id,string"`
	LabelName          string `json:"labelName" validate:"required,max=63"`
	SubscribeEnable    *bool  `json:"subscribeEnable,optional,string"`
	SubscribeFrequency string `json:"subscribeFrequency,optional"`
}

type UpdateLabelSubscribeReq struct {
	ID                 int64  `form:"id,string"`
	SubscribeEnable    *bool  `form:"enable,optional,string"`
	SubscribeFrequency string `form:"frequency,optional"`
}

type UpdateModeRequestVo struct {
	Alias            string        `json:"alias"`
	Fields           []FieldDefine `json:"fields,optional"`
	ModelDescription string        `json:"modelDescription,optional"`
}

type UpdateNameVo struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

type UpdateTemplateBaseInfoReq struct {
	ID          int64  `form:"id,string" json:"id,string"`
	Name        string `form:"name,string" json:"name,optional" validate:"max=63"`
	Description string `form:"description,string" json:"description,optional" validate:"max=255"`
}

type UpdateTemplateFieldsAndDescReq struct {
	Alias       string         `json:"alias" validate:"omitempty,max=63,alias"`
	Fields      []*FieldDefine `json:"fields,optional" validate:"min=1"`
	Description string         `json:"modelDescription,optional" validate:"omitempty,max=255"`
}

type UpdateTemplateSubscribeReq struct {
	ID                 int64  `form:"id,string"`
	SubscribeEnable    *bool  `form:"enable,optional,string"`
	SubscribeFrequency string `form:"frequency,optional"`
}

type UpdateUnsDto struct {
	Id                            int64                  `json:"id,optional"`
	Name                          string                 `json:"name,optional"`
	DisplayName                   string                 `json:"displayName,optional"`
	PathType                      int                    `json:"pathType,optional"`
	ReferUns                      string                 `json:"referUns,optional"`
	ReferIds                      []int64                `json:"referIds,optional"`
	ReferTable                    string                 `json:"referTable,optional"`
	RefFields                     []FieldDefine          `json:"refFields,optional"`
	ReferModelId                  string                 `json:"referModelId,optional"`
	Alias                         string                 `json:"alias"`
	ModelId                       *int64                 `json:"modelId,optional,string"`
	ModelAlias                    *string                `json:"modelAlias,optional"`
	ParentAlias                   *string                `json:"parentAlias,optional"`
	ParentId                      *int64                 `json:"parentId,optional,string"`
	DataType                      *int16                 `json:"dataType,optional,string"`
	Fields                        []FieldDefine          `json:"fields,optional"`
	DataPath                      string                 `json:"dataPath,optional"`
	Description                   string                 `json:"description,optional"`
	Refers                        []InstanceField        `json:"refers,optional"`
	Expression                    string                 `json:"expression,optional"`
	StreamOptions                 StreamOptions          `json:"streamOptions,optional"`
	AddFlow                       *bool                  `json:"addFlow,optional"`
	AddDashBoard                  *bool                  `json:"addDashBoard,optional"`
	Save2db                       *bool                  `json:"save2db,optional"`
	RetainTableWhenDeleteInstance *bool                  `json:"retainTableWhenDeleteInstance,optional"`
	Frequency                     string                 `json:"frequency,optional"`
	Extend                        map[string]interface{} `json:"extend,optional"`
	LabelNames                    []string               `json:"labelNames,optional"`
	RefSource                     string                 `json:"refSource,optional"`
	ValueType                     string                 `json:"valueType,optional"`
	InitValue                     interface{}            `json:"initValue,optional"`
	StrMaxLen                     *int                   `json:"strMaxLen,optional,string"`
	AccessLevel                   string                 `json:"accessLevel,optional"`
}

type UserCreateReq struct {
	ID        string        `json:"id,optional"`
	Username  string        `json:"username"`
	Password  string        `json:"password"`
	Enabled   *bool         `json:"enabled,optional"`
	Email     string        `json:"email,optional"`
	FirstName string        `json:"firstName,optional"`
	Phone     string        `json:"phone,optional"`
	Source    string        `json:"source,optional"`
	RoleList  []RoleSummary `json:"roleList,optional"`
}

type UserDeleteReq struct {
	ID string `path:"id"`
}

type UserInfoVO struct {
	Sub               string         `json:"sub"`
	PreferredUsername string         `json:"preferredUsername"`
	Email             string         `json:"email,optional"`
	EmailVerified     bool           `json:"email_verified,optional"`
	FirstName         string         `json:"firstName,optional"`
	Enabled           bool           `json:"enabled,optional"`
	HomePage          string         `json:"homePage,optional"`
	RoleList          []RoleInfo     `json:"roleList,optional"`
	ResourceList      []ResourceInfo `json:"resourceList,optional"`
	DenyResourceList  []ResourceInfo `json:"denyResourceList,optional"`
}

type UserManageItem struct {
	ID                string        `json:"id"`
	Email             string        `json:"email,optional"`
	EmailVerified     bool          `json:"emailVerified,optional"`
	FirstName         string        `json:"firstName,optional"`
	PreferredUsername string        `json:"preferredUsername"`
	Sub               string        `json:"sub,optional"`
	Enabled           bool          `json:"enabled,optional"`
	RoleList          []RoleSummary `json:"roleList,optional"`
	FirstTimeLogin    int           `json:"firstTimeLogin,optional"`
	TipsEnable        int           `json:"tipsEnable,optional"`
	HomePage          string        `json:"homePage,optional"`
	Phone             string        `json:"phone,optional"`
	Source            string        `json:"source,optional"`
}

type UserManagePageReq struct {
	PageNo            int64  `json:"pageNo,optional"`
	PageSize          int64  `json:"pageSize,optional"`
	PreferredUsername string `json:"preferredUsername,optional"`
	FirstName         string `json:"firstName,optional"`
	Email             string `json:"email,optional"`
	RoleName          string `json:"roleName,optional"`
	Enabled           *bool  `json:"enabled,optional"`
}

type UserManagePageResp struct {
	Code     int64            `json:"code"`
	PageNo   int64            `json:"pageNo"`
	PageSize int64            `json:"pageSize"`
	Total    int64            `json:"total"`
	Data     []UserManageItem `json:"data"`
}

type UserResetPwdReq struct {
	UserID      string `json:"userId"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	NewPassword string `json:"newPassword"`
}

type UserSetRoleReq struct {
	UserID   string        `json:"userId"`
	Type     int           `json:"type,optional"`
	RoleList []RoleSummary `json:"roleList,optional"`
}

type UserUpdateReq struct {
	UserID         string        `json:"userId"`
	Username       string        `json:"username,optional"`
	Password       string        `json:"password,optional"`
	Enabled        *bool         `json:"enabled,optional"`
	Email          string        `json:"email,optional"`
	FirstName      string        `json:"firstName,optional"`
	Phone          string        `json:"phone,optional"`
	FirstTimeLogin *int          `json:"firstTimeLogin,optional"`
	TipsEnable     *int          `json:"tipsEnable,optional"`
	HomePage       string        `json:"homePage,optional"`
	RoleList       []RoleSummary `json:"roleList,optional"`
	OperateRole    *bool         `json:"operateRole,optional"`
	Source         string        `json:"source,optional"`
}

type UuidRequest struct {
	Uid string `path:"uid"`
}

type WithAlias struct {
	Alias string `json:"alias" form:"alias"` // 别名
}

type WithCode struct {
	Code string `json:"code,optional"`
}

type WithGroupCode struct {
	GroupCode string `json:"groupCode,optional"` // id
	Code      string `json:"code,optional"`
}

type WithID struct {
	ID int64 `json:"id,optional" form:"id,optional"` // id
}

type WithIDOrCode struct {
	ID   int64  `json:"id,optional"` // id
	Code string `json:"code,optional"`
}

type WithIDStr struct {
	ID int64 `json:"id,string,optional"` // id
}

type WithUid struct {
	Uid string `path:"uid"`
}
