// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2-1

package handler

import (
	"net/http"
	"time"

	coreapikey "backend/internal/handler/core/apikey"
	coreasset "backend/internal/handler/core/asset"
	coreauth "backend/internal/handler/core/auth"
	corecliauth "backend/internal/handler/core/cliauth"
	coreflow "backend/internal/handler/core/flow"
	corei18n "backend/internal/handler/core/i18n"
	coreiam "backend/internal/handler/core/iam"
	coresystem "backend/internal/handler/core/system"
	coreuns "backend/internal/handler/core/uns"
	openapiv1auth "backend/internal/handler/openapi/v1/auth"
	openapiv1flow "backend/internal/handler/openapi/v1/flow"
	openapiv1info "backend/internal/handler/openapi/v1/info"
	openapiv1platform "backend/internal/handler/openapi/v1/platform"
	openapiv1uns "backend/internal/handler/openapi/v1/uns"
	"backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Permission},
			[]rest.Route{
				{
					// 获取 API Key 列表
					Method:  http.MethodGet,
					Path:    "/api-keys",
					Handler: coreapikey.ApiKeyListHandler(serverCtx),
				},
				{
					// 创建 API Key
					Method:  http.MethodPost,
					Path:    "/api-keys",
					Handler: coreapikey.ApiKeyCreateHandler(serverCtx),
				},
				{
					// 更新 API Key
					Method:  http.MethodPut,
					Path:    "/api-keys/:apiKeyId",
					Handler: coreapikey.ApiKeyUpdateHandler(serverCtx),
				},
				{
					// 删除 API Key
					Method:  http.MethodDelete,
					Path:    "/api-keys/:apiKeyId",
					Handler: coreapikey.ApiKeyDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core/common"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Permission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/asset-bindings",
					Handler: coreasset.AssetBindHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/asset-bindings/:id",
					Handler: coreasset.AssetUnbindHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/assets",
					Handler: coreasset.AssetListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/assets/:fileId",
					Handler: coreasset.AssetDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/assets/:fileId/download",
					Handler: coreasset.AssetDownloadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Permission},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/assets",
					Handler: coreasset.AssetUploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core"),
		rest.WithTimeout(300000*time.Millisecond),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: coreauth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/core/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/config",
					Handler: coreauth.CurrentUserConfigGetHandler(serverCtx),
				},
				{
					Method:  http.MethodPatch,
					Path:    "/config",
					Handler: coreauth.CurrentUserConfigPatchHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/config",
					Handler: coreauth.CurrentUserConfigPutHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: coreauth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/me",
					Handler: coreauth.CurrentUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/password",
					Handler: coreauth.CurrentUserPasswordUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/profile",
					Handler: coreauth.CurrentUserProfileUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/status",
				Handler: corecliauth.CliAuthStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/core/cli-auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/bind",
					Handler: corecliauth.CliAuthBindHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core/cli-auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Permission},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/flows",
					Handler: coreflow.FlowListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flows",
					Handler: coreflow.FlowCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/flows/:flowId",
					Handler: coreflow.FlowDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/flows/:flowId",
					Handler: coreflow.FlowUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/flows/:flowId",
					Handler: coreflow.FlowDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/flows/:flowId/data",
					Handler: coreflow.FlowDataSaveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flows/:flowId/deploy",
					Handler: coreflow.FlowDeployHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/flows/:flowId/mark",
					Handler: coreflow.FlowMarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/flows/:flowId/status",
					Handler: coreflow.FlowStatusUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/flows/missing-nodes",
					Handler: coreflow.FlowMissingNodeListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/flows/missing-nodes",
					Handler: coreflow.FlowMissingNodeDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flows/missing-nodes/cleanup",
					Handler: coreflow.FlowMissingNodeCleanupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/flows/node-types",
					Handler: coreflow.FlowNodeTypesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取系统语言包
				Method:  http.MethodGet,
				Path:    "/messages",
				Handler: corei18n.I18nMessagesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/core/i18n"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Permission},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/roles",
					Handler: coreiam.RoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/roles",
					Handler: coreiam.RoleCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/roles/:id",
					Handler: coreiam.RoleUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/roles/:id",
					Handler: coreiam.RoleDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: coreiam.UserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: coreiam.UserCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users/:id",
					Handler: coreiam.UserUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/:id",
					Handler: coreiam.UserDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users/:id/password/reset",
					Handler: coreiam.UserPasswordResetHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core/iam"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: coresystem.HealthzHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/metrics",
				Handler: coresystem.MetricsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: coresystem.ReadyzHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/system/config",
				Handler: coresystem.ConfigHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/core"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SessionAuth, serverCtx.Permission},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/dashboard",
					Handler: coreuns.UnsDashboardHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/export",
					Handler: coreuns.UnsExportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/export-jobs",
					Handler: coreuns.UnsExportJobCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/export-jobs/:jobId",
					Handler: coreuns.UnsExportJobDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/export/global",
					Handler: coreuns.UnsExportGlobalHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/import",
					Handler: coreuns.UnsImportHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/import-jobs",
					Handler: coreuns.UnsImportJobCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/import-jobs/:jobId",
					Handler: coreuns.UnsImportJobDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/labels",
					Handler: coreuns.UnsLabelListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/labels",
					Handler: coreuns.UnsLabelCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/labels/:id",
					Handler: coreuns.UnsLabelDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/labels/:id",
					Handler: coreuns.UnsLabelUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/labels/:id",
					Handler: coreuns.UnsLabelDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/newMsg",
					Handler: coreuns.UnsNewMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nodes",
					Handler: coreuns.UnsNodeListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/nodes",
					Handler: coreuns.UnsNodeCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/nodes/:nodeId",
					Handler: coreuns.UnsNodeDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/nodes/:nodeId",
					Handler: coreuns.UnsNodeUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/nodes/:nodeId",
					Handler: coreuns.UnsNodeDeleteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/core/uns"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/whoami",
					Handler: openapiv1auth.OpenapiWhoamiHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/flow/create",
					Handler: openapiv1flow.OpenapiFlowLegacyCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/delete",
					Handler: openapiv1flow.OpenapiFlowLegacyDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/deploy",
					Handler: openapiv1flow.OpenapiFlowLegacyDeployHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/flowdata",
					Handler: openapiv1flow.OpenapiFlowLegacyFlowDataHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/get",
					Handler: openapiv1flow.OpenapiFlowLegacyGetHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/list",
					Handler: openapiv1flow.OpenapiFlowLegacyListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/nodes",
					Handler: openapiv1flow.OpenapiFlowLegacyNodesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/flow/update",
					Handler: openapiv1flow.OpenapiFlowLegacyUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/info",
					Handler: openapiv1info.OpenapiInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/platform/getMembers",
					Handler: openapiv1platform.OpenapiPlatformGetMembersHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ApiKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/uns/attachments",
					Handler: openapiv1uns.OpenapiUnsAttachmentUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/attachments/list",
					Handler: openapiv1uns.OpenapiUnsAttachmentListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/browse",
					Handler: openapiv1uns.OpenapiUnsBrowseHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/create",
					Handler: openapiv1uns.OpenapiUnsCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/delete",
					Handler: openapiv1uns.OpenapiUnsDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/history",
					Handler: openapiv1uns.OpenapiUnsHistoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/read",
					Handler: openapiv1uns.OpenapiUnsReadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/search",
					Handler: openapiv1uns.OpenapiUnsSearchHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/unsBindFlow",
					Handler: openapiv1uns.OpenapiUnsBindFlowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/update",
					Handler: openapiv1uns.OpenapiUnsUpdateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/uns/write",
					Handler: openapiv1uns.OpenapiUnsWriteHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/openapi/v1"),
	)
}
