node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "data"
}
cluster { name = emqxcl, discovery_strategy = manual }
dashboard { listeners.http.bind = 18083 }
listeners.tcp.default { bind = "0.0.0.0:1883" }
listeners.ssl.default {
  bind = "0.0.0.0:8883"
  ssl_options {
    certfile = "${EMQX_ETC_DIR}/certs/cert.pem"
    keyfile = "${EMQX_ETC_DIR}/certs/key.pem"
    verify = verify_none
    fail_if_no_peer_cert = false
  }
}
listeners.ws.default { bind = "0.0.0.0:8083" }
listeners.wss.default {
  bind = "0.0.0.0:8084"
  ssl_options {
    certfile = "${EMQX_ETC_DIR}/certs/cert.pem"
    keyfile = "${EMQX_ETC_DIR}/certs/key.pem"
    verify = verify_none
    fail_if_no_peer_cert = false
  }
}
api_key { bootstrap_file = "etc/default_api_key.conf" }
authentication = []
authorization {
  no_match = allow
  deny_action = ignore
  sources = []
}
