networks:
  edge_network:
    driver: bridge

services:
  frontend:
    image: tier0/tier0-frontend:1.0.5-R1
    container_name: frontend
    ports:
      - "3010:3000"
      - "4000:4000"
    environment:
      - LLM_MODEL=${LLM_MODEL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_TYPE=${LLM_TYPE}
      - REACT_APP_OS_LANG=${LANGUAGE}
      - TOKEN_MAX_AGE=${TOKEN_MAX_AGE}
      - TZ=UTC
    command: >
      sh -c "
        if [ -z \"$LLM_API_KEY\" ]; then
          echo 'LLM_API_KEY为空，跳过Node.js服务启动'
          concurrently \"serve -s /app/web-dist -l 3000\"
        else
          echo 'LLM_API_KEY已配置，启动所有服务'
          concurrently \"serve -s /app/web-dist -l 3000\" \"node /app/services-express-dist/index.js\"
        fi
      "
    volumes:
      - ${DOCKER_CERTS_PATH:-/etc/docker/certs}:/certs
    networks:
      - edge_network
    restart: always
  uns:
    image: tier0/tier0-backend:1.0.5-R1
    container_name: uns
    environment:
      - LLM_MODEL=${LLM_MODEL}
      - LLM_API_KEY=${LLM_API_KEY}
      - LLM_TYPE=${LLM_TYPE}
      - REACT_APP_OS_LANG=${LANGUAGE}
      - SYS_OS_APP_TITLE=${OS_NAME}
      - SYS_OS_LOGIN_PATH=${OS_LOGIN_PATH}
      - SYS_OS_LANG=${LANGUAGE}
      - TOKEN_MAX_AGE=${TOKEN_MAX_AGE}
      - TZ=UTC
      - GRPC_POOL_CORE_SIZE=2
      - GRPC_POOL_MAX_SIZE=4
      - dbDSN=${UNS_DB_URL}
      - SINK_PG_URL=${SINK_PG_URL}
      - SINK_TSDB_URL=${SINK_TSDB_URL}
      - NODE_RED_HOST=nodered
      - NODE_RED_PORT=1880
      - SYS_OS_MULTIPLE_TOPIC=false
      - SYS_OS_VERSION=${OS_VERSION}
      - SYS_OS_AUTH_ENABLE=${OS_AUTH_ENABLE}
      - SYS_OS_LLM_TYPE=${OS_LLM_TYPE}
      - SYS_OS_MQTT_TCP_PORT=${OS_MQTT_TCP_PORT}
      - SYS_OS_MQTT_WEBSOCKET_TSL_PORT=${OS_MQTT_WEBSOCKET_TSL_PORT}
      - SYS_OS_PLATFORM_TYPE=${OS_PLATFORM_TYPE}
      - SYS_OS_ENTRANCE_URL=${BASE_URL}
      - SYS_OS_QUALITY_NAME=quality
      - SYS_OS_TIMESTAMP_NAME=timeStamp
      - SYS_OS_LAZY_TREE=${LAZY_TREE}
      - UNS_ADD_BATCH_SIZE=1000
      - IAM_PORTAINER_CLIENT_ID=${IAM_PORTAINER_CLIENT_ID:-portainer}
      - IAM_PORTAINER_CLIENT_SECRET=${IAM_PORTAINER_CLIENT_SECRET:-Tier0PortainerSecret@1304}
      - IAM_BOOTSTRAP_USERNAME=${IAM_BOOTSTRAP_USERNAME:-tier0}
      - IAM_BOOTSTRAP_PASSWORD=${IAM_BOOTSTRAP_PASSWORD:-tier0}
      - IAM_BOOTSTRAP_EMAIL=${IAM_BOOTSTRAP_EMAIL-}
    volumes:
      - ${VOLUMES_PATH}/edge/system/:/app/go-edge/system/
      - ${VOLUMES_PATH}/edge/attachment/:/app/go-edge/attachment/
      - ${VOLUMES_PATH}/edge/apps/:/app/data/apps/
      - ${DOCKER_CERTS_PATH:-/etc/docker/certs}:/certs
    ports:
      - "18998:8080"
    networks:
      - edge_network
    depends_on:
      postgresql:
        condition: service_healthy
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  emqx:
    image: emqx/emqx:5.8
    container_name: emqx
    ports:
      - "1883:1883"   # MQTT端口
      - "8883:8883"   # MQTT加密端口
      - "${OS_MQTT_WEBSOCKET_PORT:-8083}:8083"   # WebSocket端口
      - "8084:8084"   # WebSocket加密端口
      - "18083:18083" # EMQX Dashboard端口
    environment:
      - EMQX_NAME=emqx
      - EMQX_NODE__COOKIE=secretcookie # 节点通信时的cookie
      - service_logo=emqx-original.svg
      - service_description=aboutus.emqxDescription
      - service_redirect_url=/emqx/home/
      - service_account=admin
      - service_password=public
      - TZ=UTC
    volumes:
      - ${VOLUMES_PATH}/emqx/data:/opt/emqx/data
      - ${VOLUMES_PATH}/emqx/log:/opt/emqx/log
      - ${VOLUMES_PATH}/certs/tls:/opt/emqx/etc/certs:ro
      - ${VOLUMES_PATH}/emqx/config/emqx.conf:/opt/emqx/etc/emqx.conf
      - ${VOLUMES_PATH}/emqx/config/default_api_key.conf:/opt/emqx/etc/default_api_key.conf
      - ${VOLUMES_PATH}/emqx/config/acl.conf:/opt/emqx/etc/acl.conf
    restart: always
    networks:
      - edge_network
  nodered:
    image: nodered/node-red:4.1.10-22
    container_name: nodered
    user: root
    ports:
      - "1880:1880"  # Node-RED web UI端口
    environment:
      - service_logo=nodered-original.svg
      - service_description=aboutus.nodeRedDescription
      - FLOWS=/data/flows.json
      - USE_ALIAS_AS_TOPIC=false
      - TIMESTAMP_NAME=timeStamp
      - QUALITY_NAME=quality
      - TZ=UTC
      - OS_LANG=${LANGUAGE}
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_HTTP_API_PREFIX=/nodered-api
    volumes:
      - ${VOLUMES_PATH}/node-red:/data  # 使用当前目录的 data 目录
    depends_on:
      - emqx
    restart: always
    networks:
      - edge_network
  eventflow:
    image: nodered/node-red:4.1.10-22
    container_name: eventflow
    user: root
    ports:
      - "1889:1889"  # Node-RED web UI端口
    environment:
      - service_logo=nodered-original.svg
      - service_description=aboutus.nodeRedDescription
      - FLOWS=/data/flows.json
      - USE_ALIAS_AS_TOPIC=false
      - QUALITY_NAME=status
      - TIMESTAMP_NAME=timeStamp
      - TZ=UTC
      - OS_LANG=${LANGUAGE}
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_HTTP_API_PREFIX=/eventflow-api
    volumes:
      - ${VOLUMES_PATH}/eventflow:/data  # 使用当前目录的 data 目录
    restart: always
    networks:
      - edge_network
  grafana:
    image: grafana/grafana:11.5.6
    profiles:
      - grafana
    container_name: grafana
    user: root
    ports:
      - "${GRAFANA_PORT:-3000}:3000"  # Grafana web UI端口
    volumes:
      - ${VOLUMES_PATH}/grafana/data:/var/lib/grafana
      # - ${VOLUMES_PATH}/grafana/data/plugins:/var/lib/grafana/plugins  # 使用当前目录的 data 目录
    environment:
      service_logo: grafana-original.svg
      service_description: aboutus.grafanaDescription
      service_redirect_url: /grafana/home/dashboards/
      # 设置管理员用户的初始密码
      GF_SECURITY_ADMIN_PASSWORD: "supos"
      # 开启 Grafana 的 Explore 功能
      GF_EXPLORE_ENABLED: "true"
      # 安装 Grafana 插件
      # GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-mqtt-datasource,tdengine-datasource,yesoreyeram-infinity-datasource"
      # 注释掉的设置，用于改变 Grafana 用户界面的语言
      GF_VIEWER_LANGUAGE: "${GRAFANA_LANG:-en-US}"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_SERVER_ROOT_URL: "http://${ENTRANCE_DOMAIN}/grafana/home/"
      GF_USERS_DEFAULT_THEME: "light"
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: postgresql:5432
      GF_DATABASE_NAME: grafana
      GF_DATABASE_USER: postgres
      GF_DATABASE_PASSWORD: postgres
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy  # 依赖 PostgreSQL 的健康状态
    networks:
      - edge_network
  portainer:
    image: portainer/portainer-ce:2.33.5
    container_name: portainer
    environment:
      service_logo: portainer.svg
    command: --admin-password="$$2y$$05$$ZTAqF7Tn.hil8X.ifVmQTuKiJQoZDiKDW3t1lRR2/VPR06QoHv4AC" --http-enabled --base-url /portainer/home --trusted-origins ${ENTRANCE_DOMAIN}
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_PATH}/portainer:/data
    networks:
      - edge_network
  postgresql:
    image: timescale/timescaledb:2.20.0-pg17
    container_name: postgresql
    environment:
      TZ: UTC  # 设置容器时区
      service_logo: postgresql-original.svg
      service_description: aboutus.postgresqlDescription
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ${VOLUMES_PATH}/postgresql/conf/postgresql.conf:/etc/postgresql/custom.conf
      - ${VOLUMES_PATH}/postgresql/pgdata:/var/lib/postgresql/data # 持久化数据
      - ${VOLUMES_PATH}/postgresql/init-scripts:/docker-entrypoint-initdb.d  # 加载初始化脚本
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/custom.conf
    healthcheck:
      test: ["CMD-SHELL", "psql -U postgres -d postgres -c '\\dt supos.supos_resource' | grep -q 'supos_resource'"]
      interval: 15s
      timeout: 15s
      retries: 60
      start_period: 120s
      start_interval: 10s
    restart: always
    networks:
      - edge_network
  tsdb:
    image: timescale/timescaledb:2.20.0-pg17
    container_name: tsdb
    environment:
      TZ: UTC  # 设置容器时区
      service_logo: postgresql-original.svg
      service_description: aboutus.postgresqlDescription
      POSTGRES_PASSWORD: postgres
    ports:
      - "2345:5432"
    volumes:
      - ${VOLUMES_PATH}/tsdb/conf/postgresql.conf:/etc/postgresql/custom.conf
      - ${VOLUMES_PATH}/tsdb/data:/var/lib/postgresql/data # 持久化数据
      - ${VOLUMES_PATH}/tsdb/init-scripts:/docker-entrypoint-initdb.d  # 加载初始化脚本
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/custom.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
      start_interval: 60s
    restart: always
    networks:
      - edge_network
  kong:
    image: kong:3.9.0
    container_name: kong
    environment:
      KONG_WORKER_STATE_UPDATE_FREQUENCY: 30
      KONG_DB_CACHE_TTL: 600
      KONG_NGINX_WORKER_PROCESSES: 2
      KONG_LUA_GC_PAUSE: 100            # 提高暂停率，降低 GC 触发频率
      KONG_LUA_GC_STEPMUL: 200          # 增加单次回收强度
      service_logo: RoutingManagement.svg
      service_description: aboutus.kongDescription
      service_redirect_url: /routing-management
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql
      KONG_PG_PASSWORD: postgres
      KONG_PG_USER: postgres
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_SSL_CERT: /etc/kong/ssl/cert.pem
      KONG_SSL_CERT_KEY: /etc/kong/ssl/key.pem
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_PLUGINS: bundled,supos-auth-checker,supos-url-transformer
      KONG_PG_POOL_SIZE: 2
      KONG_LOG_LEVEL: error
      KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE: 2048m
      KONG_NGINX_PROXY_CLIENT_MAX_BODY_SIZE: 2048m
      KONG_NGINX_HTTP_PROXY_CONNECT_TIMEOUT: 300000
      KONG_NGINX_HTTP_PROXY_SEND_TIMEOUT: 300000
      KONG_NGINX_HTTP_PROXY_READ_TIMEOUT: 300000
    volumes:
      - ${VOLUMES_PATH}/certs/tls:/etc/kong/ssl:ro
      - ${VOLUMES_PATH}/kong/kong_config.yml:/etc/kong/kong_config.yml
      - ${VOLUMES_PATH}/kong/start.sh:/usr/local/bin/start.sh
      - ${VOLUMES_PATH}/kong/kong-plugin-auth-checker:/usr/local/share/lua/5.1/kong/plugins/supos-auth-checker
      - ${VOLUMES_PATH}/kong/kong-plugin-url-transformer:/usr/local/share/lua/5.1/kong/plugins/supos-url-transformer
    ports:
      - "${ENTRANCE_PORT:-8088}:8000"
      - "${ENTRANCE_SSL_PORT:-8443}:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - emqx
      - uns
      - postgresql
    command: ["/bin/sh", "/usr/local/bin/start.sh"]
    restart: always  # 确保 Kong 自动重启
    networks:
      - edge_network
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    profiles:
      - minio
    environment:
      - service_logo=minio-original.svg
      - service_description=aboutus.minioDescription
      - service_redirect_url=/minio/home/
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=adminpassword
      - MINIO_BROWSER_REDIRECT_URL=${BASE_URL}/minio/home
    ports:
      - "9000:9000"  # Web UI 端口
      - "9001:9001"  # Admin API 端口 (如果需要访问管理接口)
    volumes:
      - ${VOLUMES_PATH}/minio/data:/data  # 数据存储位置
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - edge_network
