// ⚠️ 从 apps/web/src/theme/theme-token.ts 同步（antd token → ui CSS 变量桥接），修改时保持两边一致
export default {
  token: {
    borderRadius: 3,
    colorBgElevated: 'var(--ui-bg-color)',
    colorFill: 'var(--ui-color-fill)',
    colorTextPlaceholder: 'var(--ui-t-gray-color-30)',
    colorText: 'var(--ui-text-color)',
    colorTextDescription: 'var(--ui-text-color)',
    colorTextDisabled: 'var(--ui-select-d-color)',
    colorPrimary: 'var(--ui-theme-color)',
    boxShadowSecondary: '1px 1px 10px 2px var(--ui-boxshadow-color)',
    colorPrimaryHover: 'var(--ui-theme-color)',
    colorPrimaryActive: 'var(--ui-theme-button-active-color)',
    colorBgMask: 'var(--ui-modal-mask-bg)',
    colorFillSecondary: 'var(--ui-fill-secondary)',
    colorFillTertiary: 'var(--ui-fill-tertiary)',
  },
  components: {
    Segmented: {
      itemHoverColor: '#161616',
    },
    Menu: {
      itemBg: 'var(--ui-bg-color)',
      itemColor: 'var(--ui-text-color)',
      itemHoverColor: 'var(--ui-text-color)',
      itemHoverBg: 'var(--ui-menu-hover-color)',
      itemSelectedBg: 'var(--ui-menu-active-color)',
      subMenuItemBg: 'var(--ui-bg-color)',
      popupBg: 'var(--ui-bg-color)',
      itemSelectedColor: 'var(--ui-text-color)',
      horizontalItemSelectedColor: 'var(--ui-theme-color)',
    },
    Tag: {
      defaultColor: 'var(--ui-text-color)',
      defaultBg: 'var(--ui-tag-color)',
    },
    Dropdown: {
      colorText: 'var(--ui-text-color)',
      colorBgElevated: 'var(--ui-bg-color)',
      controlItemBgHover: 'var(--ui-menu-hover-color)',
      controlItemBgActive: 'var(--ui-menu-active-color)',
      controlItemBgActiveHover: 'var(--ui-menu-active-color)',
    },
    Select: {
      colorTextDescription: 'var(--ui-text-color)',
      activeBorderColor: 'var(--ui-theme-color)',
      activeOutlineColor: 'transparent',
      colorBgContainerDisabled: 'var(--ui-t-button-d-color)',
      zIndexPopup: 9001,
      colorBgElevated: 'var(--ui-input-color)',
      colorText: 'var(--ui-text-color)',
      selectorBg: 'var(--ui-input-color)',
      optionSelectedBg: 'var(--ui-select-active-color)',
      colorBgContainer: 'var(--ui-input-color)',
      multipleItemBg: 'var(--ui-fill-secondary)',
    },
    Input: {
      colorBgContainer: 'var(--ui-input-color)',
      colorText: 'var(--ui-text-color)',
      colorBgContainerDisabled: 'var(--ui-t-button-d-color)',
      activeBorderColor: 'var(--ui-theme-color)',
      activeShadow: 'none',
    },
    Message: {
      zIndexPopup: 9001,
    },
    Form: {
      labelColor: 'var(--ui-text-color)',
    },
    InputNumber: {
      colorBgContainer: 'var(--ui-input-color)',
    },
    Modal: {
      contentBg: 'var(--ui-modal-color)',
    },
    Button: {
      colorPrimary: 'var(--ui-primary-button-bg, var(--ui-theme-color))',
      colorPrimaryHover: 'var(--ui-primary-button-bg-hover, var(--ui-theme-button-hover-color))',
      colorPrimaryTextHover: 'var(--ui-primary-button-bg-hover, var(--ui-theme-button-hover-color))',
      colorPrimaryActive: 'var(--ui-primary-button-bg-hover, var(--ui-theme-button-active-color))',
      colorTextLightSolid: 'var(--ui-primary-button-text, #fff)',
      defaultShadow: 'none',
      primaryShadow: 'none',
      dangerShadow: 'none',
      defaultBg: 'var(--ui-bg-color)',
      defaultHoverBg: 'var(--ui-bg-color)',
      defaultHoverColor: 'var(--ui-theme-button-hover-color)',
      colorLink: 'var(--ui-theme-color)',
      colorLinkHover: 'var(--ui-theme-button-hover-color)',
      colorPrimaryBg: 'var(--ui-primary-bg)',
      colorPrimaryBgHover: 'var(--ui-primary-bg-hover)',
      colorFill: 'var(--ui-fill-tertiary)',
    },
    Tabs: {
      itemSelectedColor: 'var(--ui-theme-color)',
      inkBarColor: 'var(--ui-theme-color)',
    },
    DatePicker: {
      colorBgContainer: 'var(--ui-input-color)',
      colorPrimary: 'var(--ui-theme-color)',
      cellActiveWithRangeBg: 'var(--ui-active-with-range-bg)',
      controlItemBgActive: 'var(--ui-active-with-range-bg)',
      colorIcon: '#848484',
      cellHoverBg: 'var(--ui-cell-hover-bg)',
    },
    Radio: {
      colorPrimary: 'var(--ui-theme-color)',
      buttonBg: 'var(--ui-bg-color)',
      buttonCheckedBg: 'var(--ui-bg-color)',
      radioSize: 18,
      dotSize: 8,
      motionDurationMid: '0s',
      motionDurationSlow: '0s',
    },
    Table: {
      colorPrimary: 'var(--ui-theme-color)',
      colorBgContainer: 'var(--ui-bg-color)',
      // headerBg: 'var(--ui-table-head-color)',
      headerColor: 'var(--ui-text-color)',
      // rowHoverBg: 'var(--ui-menu-hover-color)',
      headerBorderRadius: 0,
      headerSplitColor: 'var(--ui-line-color)',
      headerFilterHoverBg: 'var(--ui-charttop-bg-color)',
      headerSortHoverBg: 'var(--ui-charttop-bg-color)',
      headerSortActiveBg: 'var(--ui-charttop-bg-color)',
      borderColor: 'var(--ui-line-color)',
      headerBg: 'var(--ui-bg-color)',
      rowHoverBg: 'var(--ui-charttop-bg-color)',
      bodySortBg: 'var(--ui-charttop-bg-color)',
    },
    Typography: {
      colorLink: 'var(--ui-theme-color)',
      colorLinkHover: 'var(--ui-theme-button-hover-color)',
      colorLinkActive: 'var(--ui-theme-color)',
    },
    Checkbox: {
      colorPrimary: 'var(--ui-theme-color)',
      colorPrimaryHover: 'none',
      motionDurationFast: '0s',
      motionDurationMid: '0s',
      motionDurationSlow: '0s',
    },
    Tree: {
      colorPrimary: 'var(--ui-theme-color)',
      nodeSelectedBg: 'var(--ui-select-active-color)',
      nodeHoverBg: 'var(--ui-fill-secondary)',
      colorBgContainer: 'var(--ui-bg-color)',
    },
    TreeSelect: {
      colorPrimary: 'var(--ui-theme-color)',
      nodeSelectedBg: 'var(--ui-select-active-color)',
      nodeHoverBg: 'var(--ui-fill-secondary)',
      colorBgContainer: 'var(--ui-bg-color)',
    },
    Switch: {
      colorPrimary: 'var(--ui-theme-color)',
      handleShadow: '',
    },
    Pagination: {
      itemBg: 'var(--ui-bg-color)',
      itemActiveBg: 'var(--ui-bg-color)',
    },
  },
};
